### ISSUE TITLE
Render multiple <mdiv> at once

### ISSUE THREAD

**Issue by wergo** [rism-digital/verovio#1262]
Related to the discussion in #1141, #509, and #154, I wanted to raise a related issue, that is how to render more than one `<mdiv>` at once. 

Background are collection of pieces, such as Op. 119 by Beethoven where you would encode each of the 11 pieces as a separate `<mdiv>` within one MEI file, similar to an entire sonata or symphony, as suggested in the guidelines: https://music-encoding.org/guidelines/v4/content/shared.html#sharedDivisionsBody. 

Many of the pieces/mdiv end and start on the same page, as here No. 7 end, 8, and 9: 
<img width="884" alt="Beethoven_Op119-7-9" src="https://user-images.githubusercontent.com/45632600/72452214-76d15b80-37bd-11ea-9b92-60c6f567db4c.png">

It would be great to have an option to render all (or a selection of) mdivs of a MEI file to be able to get mdiv transitions within one page. I am aware that this might not be easy to implement in Verovio. 

Addendum: In Beethoven's variations on a Swiss Air WoO 64 in Breitkopf & Härtel you have even four `<mdiv>`s on one page; two of them even sharing the same line/system:
<img width="875" alt="Beethoven_WoO64" src="https://user-images.githubusercontent.com/45632600/72452321-a5e7cd00-37bd-11ea-8ac7-a160379cf61c.png">

**Comment by palgranum** [comment]
Is there any hope that this feature will be prioritized in foreseeable future?
As @wergo points out, there seems to be no other way/workaround for engraving (parts of) multiple movements/mdivs on the same page.

In addition to needing to solve this problem, I would also like to be able to render any page from a (mei file) score that might contain multiple mdivs without having to switch mdivs and wait for the toolkit to reload and relayout. This switching operation can last several seconds and prevents a practical implementation of displaying the score interactively in real-time without employing some complex mdiv switching caching operation.

**Comment by lpugin** [comment]
The problem with multiple mdiv is that you can have very different score definitions. For example, a movement with 20 instruments, followed by another one of 5, or the opposite. This will never work well with dynamic rendering. However, I am happy to guide you if you want help for trying to implement something.

**Comment by kseniaosipova** [comment]
@lpugin yes, it can be different, but still required the possibility to render 2 or more movements at once. So, could we consider this as approved, if we will start to propose the implementation of Rendering multiple <mdiv> at once?

**Comment by lpugin** [comment]
The first step will be to come up at that appropriate page-based representation of the last example above. See https://www.verovio.org/structure.xhtml 
Once this is in place we can look in the code what needs to be changed

**Comment by Pryadka** [comment]
Hello @lpugin . I started experimenting with all <mdiv> rendering. The main idea is to add multiply system to first page during `ConvertToPageBasedDoc` processing.  Every <score> from each <mdiv> is transformed to 'system' and then the system is added to page. So pages contain one page as it was before and this page has as many systems as many <mdiv> were in input data file. Everything looks ok except the result. 
![two-mdivs](https://user-images.githubusercontent.com/5373894/83148009-b3f91300-a0f8-11ea-9ac0-d827949bbd3d.png)

Source .mei
[fish.mei.txt](https://github.com/rism-ch/verovio/files/4695766/fish.mei.txt)

The question is if this approach is correct and where the error is. 
By the way first mdiv should look like this
![image](https://user-images.githubusercontent.com/5373894/83147673-4cdb5e80-a0f8-11ea-8334-25b9ae37d2e1.png)

**Comment by lpugin** [comment]
As I said, before starting to implement anything we need to clarify the structure. So far we have
```xml
<pages>
	<page>
		<system>
			<scoreDef/>
			<measure/>
		</system>
                <!-- The next system below -->
		<system>
			<!-- ... -->
		</system>
	</page>
</pages>
```
This does not allow to represent things like - I would be interested to hear thoughts how we should represent it
![image](https://user-images.githubusercontent.com/689412/83152449-1bfe2800-a0fe-11ea-94af-db76eb890312.png)

**Comment by kepper** [comment]
There is no equivalent to `<section>` or `<mdiv>` yet, and admittedly, they wouldn't work well here. Instead of such a container element, we need a milestone type thing, just like a `<pb/>`or `<sb/>` in regular MEI. Let's assume we add something like `<secB> / <sectionBreak>` or `<mb/> / <mdivBreak/>`. Especially the mdiv-breaking milestone would need an attribute to indicate that the staff lines are to be disconnected. It could either contain or be followed by a `<scoreDef/>` element. What do you think?

**Comment by lpugin** [comment]
Yes, `<mdiv>`, `<section>`, but also `<ending>` needs to have milestone equivalent. I think your idea of an attribute on `<mdivBreak>` would work.
One other idea could be to have a `<systemGrp>`, so we would have something like (still leaving milestones out for now):
```xml
<pages>
	<page>
		<system>
			<scoreDef/>
			<measure/>
		</system>
		<systemGrp>
			<!-- The next system below -->
			<system>
				<!-- ... -->
			</system>
			<!-- The next system on the side -->
			<system>
				<!-- ... -->				
			</system>			
		</systemGrp>
	</page>
</pages>
```
But I don't like it too much

**Comment by kepper** [comment]
Instead of a `<systemGrp>`, I think the alternative would be to have two systems without grouping, but with graphical placement (like `@x`, `@y`, `@width`, `@height`, `@rotation`). That way, we could cover quite some 20th century music as well, especially if we'd were to add `@next`/ `@prev` as well. But that would go even more in the visual direction, and may make it harder to go back to regular MEI.

**Comment by lpugin** [comment]
Yes, I think it should also work without `@x` and `@y` positioning. I am still unsure if the attribute for specifying that the system should be a continuation should go an the `<mdivBreak>` or instead on the `<system>`. Actually, looking at it, I am also not sure how you would represent this in standard MEI. It seems that `<sb/>` is not allowed between `<mdiv>`...

**Comment by kepper** [comment]
you would put that further inside, before the first measure / inside section.

**Comment by lpugin** [comment]
Which mean that we probably want to put the attribute on `<system>`. Something like `<system cont="true">` would mean no `<sb/>` when converting from / to standard MEI

**Comment by kepper** [comment]
yes, but only when you allow multiple `<system>` elements for one horizontal row. If you stick with just one, you need a milestone element.

**Comment by lpugin** [comment]
Yes, I meant "no `<sb/>`" on that particular point. So maybe a better attribute would be `<system brake="false"/>`

**Comment by lpugin** [comment]
@Pryadka the proper way to implement this is first to move up the page-based transformation from the content of the selected `<score>` to the root of the Doc. (If you don't do this the rendering is never going to work.) These means turning `<mdiv>` and `<score>` into corresponding milestones - as explained by @kepper. They need inherit from `SystemElement` and `BoundaryStartInterface`. You can follow the example of `Section`.

Then, `Doc::ConvertToPageBasedDoc` should not start from the `Score` retrived with`GetScore()` but from itself (so `this->Process`). For every Score, you are going to add a System (which is similar to what you tried).

Once this is in place, you should be able to
- Load an MEI document
- Convert it to page-based
- Output the MEI (page-based and score-based, the latter should be identical to the input file)

For now, the page-based with be one System per Score - Assuming we have @break="none"` on every system, then this would mean one single page with all the music (all mdivs) - on one line. This will be the starting point for layout calculation!

(The next thing will be to move the Doc::m_mdivScoreDef to Score)

**Comment by Pryadka** [comment]
@lpugin The approach with all mdivs in one line is not good. Each score has own scoreDef and taking in account current architecture with common scoreDef for entire document it's not easy to modify layouting process. I have another idea. We can loyout each mdiv separately and than sew generated pages in one page set. As far as each mdiv rendering is independent from others, we can try to do each rendering in it's own thread.

**Comment by lpugin** [comment]
> The approach with all mdivs in one line is not good

This is not what I said. Quite on the contrary, I said to have each `<score>` in one line. (BTW the issue is about rendering multiple score elements, not multiple mdivs)

> Each score has own scoreDef and taking in account current architecture with common scoreDef for entire document it's not easy to modify layouting process.

Yes, this is precisely what I am proposing to change: "move Doc::m_mdivScoreDef to Score" meaning that each Score has its own top-level scoreDef.

I am not against a solution that can be performed in distinct threads. But I am against a proposal that cannot take into account cases where the score break appears in the middle of a system (again, please consider the example given by above with VAR III starting in the middle of the system). For such a case to work, sewing pages it not good. You need first to layout entire Score elements on distinct systems. In the example given, each variation will be one system. We could imagine this being done in parallel, but of course it does not have to. Once this is done, we can start casting off systems by sequentially adding them and inserting system break. This cannot be done in parallel anymore. However, If you decide that a score should never start in the middle of the system, then you can also do the insertion of system breaks - but not the one of page break because a score can start on in the middle of a page. Again, you can add another limitation and decide that a score should never start in the middle of a page, then you can do one step further in parallel, which is inserting page breaks. Sewing pages would work here, but not in the two other cases.

**Comment by lpugin** [comment]
I am looking at handling two different cases. For the variation example, I think it would be acceptable only to have `<scoreDef>` elements for encoding the beginning of each variation. Each variation could also be wrapped within a corresponding `<section>`. This would make it relatively straightforward to render them continuously in one system. We would still need to have a way to indicate if the brace and label should be redrawn or not since only relying on their presence looks a bit arbitrary to me. Any thoughts?

This still leave the case of multiple `<mdiv>`. I understand this might be more correct in some cases - even though for some variations I am not convinced it really is. I cannot reasonably see multiple `<mdiv>` rendered continuously within one system. However, if we assume there will always be a system break at the beginning of each `<mdiv>` then it should be feasible.

**Comment by lpugin** [comment]
We still need to work on the page-based customization to implement this. It looks like a major change will be that `<pages>` will need to be moved up as child of `<body>` and not of `<mdiv>` anymore. Then, obviously `<mdiv>` and `<score>` will need to have a corresponding milestone element `<mdivb>` and `<scoreb>` as we currently already have for `<section>`.
