### ISSUE TITLE
[QUESTION] Usage of this pointer

### ISSUE THREAD

**Issue by DavidBauer1984** [rism-digital/verovio#2147]
The codebase uses `this->` in many places to access class members and member functions. It is used quite a lot, but not consistently everywhere. The only functional difference I can think of is when there is a local variable with the same name as a class member. However, this is very unlikely, since class members start with "m_" while local variables do not. Even if the member function is virtual, then which function is called during execution does not depend on whether `this` is used or not. So basically, it could be omitted. What is the reason for using it? Is it historical?

**Comment by lpugin** [comment]
Yeah, you are right the codebase is not consistent on that point. It should certainly be omitted for class members since they do start with `m_`. I am less sure what to decide for methods event though you are right it is not relevant for execution. I guess having (i.e., typing) `this->` is a way to trigger the autocomplete and is one reason why it is there in many places. I would suggest:
* omit them for class members
* have it for methods

Does it sound reasonable?

**Comment by DavidBauer1984** [comment]
Yes, sounds good to me. For me it would be helpful to have a clear convention. Maybe we can put this in the coding guidelines.

Here is a related [discussion](https://stackoverflow.com/questions/9590820/should-i-use-this-within-a-class) on StackOverflow. Apparently, some people use it and some do not.

**Comment by lpugin** [comment]
Added here https://github.com/rism-digital/verovio-reference-book/commit/9649c8c6e7ab2ec2e2c68d3adcd65963f09c876e (new documentation in preparation)
