### ISSUE TITLE
Verovio does not auto-detect MEI files if there is a line break after opening "<mei" 

### ISSUE THREAD

**Issue by karend27** [rism-digital/verovio#2160]
With our MP Editor generated files, we noticed that if there is a line break after the opening of the initial <mei> tag, Verovio cannot parse the file. 

For example, our MP editor generated an MEI file that begins like this:
`<mei`
```
    xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev"
    xmlns:xlink="http://www.w3.org/1999/xlink">
```

and Verovio cannot parse this.

But if the first break is removed it parses fine (even if there is a break later in the tag):

```
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev"
    xmlns:xlink="http://www.w3.org/1999/xlink">
```

We are looking into seeing if we can make sure there is no break in the generated XML although it is still correct XML.

**Comment by lpugin** [comment]
I suspect this to be related to the function that tries to detect the input format. Could you try setting the input format explicitly with `--input-from mei` or `{ "inputFrom": "mei" }` ?

**Comment by karend27** [comment]
@JRegimbal is this a possibility?

**Comment by JRegimbal** [comment]
@lpugin Adding `-f mei` does result in the expected behavior, so that (or `{ "inputFrom": "mei" }`) should be sufficient. It does end up meaning that any other site or service using Verovio that doesn't include that will fail to load these MEI files, which is obviously not ideal.

I took a quick look yesterday and it seems the issue is in [lines 227-232 of `src/toolkit.cpp`](https://github.com/rism-digital/verovio/blob/b3a1b985d532d0e9ade9ef8a41ef55c4fc8022ed/src/toolkit.cpp#L227-L232) where it checks explicitly for `<mei>` or `<mei `.

**Comment by lpugin** [comment]
> I took a quick look yesterday and it seems the issue is in lines 227-232 of src/toolkit.cpp where it checks explicitly for `<mei>` or `<mei `.

Yes, this is where the problem occurs. @JRegimbal do you want to change these to regular expressions? Another easier fix could be to return MEI for all XML files (starting with `<`) but for which a specific XML format cannot be detected. That would simply require changing this https://github.com/rism-digital/verovio/blob/b3a1b985d532d0e9ade9ef8a41ef55c4fc8022ed/src/toolkit.cpp#L273-L274 (`std::cerr` should be changed to `LogWarning`). I am fine with this easy solution.
