### ISSUE TITLE
Take `verse@visible` into account for the vertical spacing of the lyrics

### ISSUE THREAD

**Issue by samuelbradshaw** [rism-digital/verovio#2241]
I'm looking for a way to temporarily hide a lyric verse so that it's skipped over when rendering to SVG, without leaving a gap.
- Hiding a verse with CSS after it's been rendered leaves a gap, because the height of a system doesn't adjust after rendering.
- Adding `visible="false"` to a verse in the MEI before rendering to SVG doesn't work, because that maps to `visibility="hidden"` in the SVG, which still takes up space (if I understand correctly from reading other issues).
- Commenting out a verse in the MEI with `<!-- XML comments -->` partially works – see screenshot. I tried to comment out verses 1, 5, and 6. Verses 5 and 6 went away like I hoped they would, but verse 1 left a gap.

<img width="870" alt="Screen Shot 2021-06-10 at 8 54 30 PM" src="https://user-images.githubusercontent.com/7323052/121624068-13893e80-ca2e-11eb-836a-c8a45e973add.png">

Here's the sample file from the screenshot with verses 1, 5, and 6 commented out:
[116ComeFollowMeTEST3-commented.mei.zip](https://github.com/rism-digital/verovio/files/6635464/116ComeFollowMeTEST3-commented.mei.zip)

Is there any way to prevent an element from rendering, without removing it from the MEI file entirely? And any idea why commenting verses out in the MEI didn't work? :)

**Comment by ahankinson** [comment]
You could try running it through an XSLT prior to rendering. This has the ability to modify the XML just before Verovio renders it, so all the layout is done on the modified MEI XML, rather than needing to operate on the SVG.

**Comment by lpugin** [comment]
Adding support for `verse@visible` in the layout would be good. Looking at the code, it seems we need to modify the way `VerticalAligner::m_verseCount` works. Basically:
* Do not call `VerticalAligner::SetVerseCount` in `Staff::AlignVertically` when the verse is not visible
* Modify the way counting is perform. Currently it relies only on `verse@n`. `VerticalAligner::m_verseCount` should be changed to an array `VerticalAligner::m_verseNs` of distinct `@n` and `VerticalAligner::GetVerseCount` should return the size of the array.

**Comment by samuelbradshaw** [comment]
@ahankinson, I had a typo in my original post mentioning SVG instead of MEI (fixed). When I tried using XML comments to comment out verses, I was commenting them out in the MEI, before rendering to SVG – which I think would be equivalent to your suggestion to run it through XSLT prior to rendering. Thanks for the help, in any case! It sounds like the root issue is how the verse count is calculated.

**Comment by rettinghaus** [comment]
From my understanding of `@visible` things will not simply vanish. If you make a quarter note in a 4/4 measure invisible it will not change to a 3/4 measure. I think we had a discussion about the exact (MEI) behaviour somewhere else.

**Comment by craigsapp** [comment]
Note that there are two concepts of visibility in CSS:

(1) [visibility](https://www.w3schools.com/cssref/pr_class_visibility.asp): hidden == do not show the object, but leave space as if it were visible.
(2) [display](https://www.w3schools.com/cssref/pr_class_display.asp): none == do not show the object and do not leave space as if it were visible.

CSS visibility behaves as shown in the above example in the first post of the issue.   It would be confusing to have MEI visibility map to CSS display=none rather than CSS visibility=hidden (but this has happened elsewhere already?).

@ahankinson 's comments still apply:

> You could try running it through an XSLT prior to rendering. This has the ability to modify the XML just before Verovio renders it, so all the layout is done on the modified MEI XML, rather than needing to operate on the SVG.

MEI -> XSLT -> MEI with reduced verses -> verovio -> SVG with reduced verses (equivalent to display:none for removed verses).

https://www.w3schools.com/xml/xsl_client.asp

The procedure would be to remove all `verse@n="#"`, where `#` is a verse number to hide.   Then to move all verses down in the numbering system so that the remaining verses are renumbered starting at 1 (note the visible verse number in the music is unrelated to this process, and is stored in `<label>`).  The hidden verses can be deleted or commented out, since the output of the XSLT processing would be temporary data that is not saved.  When you want to hide another verse, you would restart the process with the original MEI score that contains all of the verses.


Here is an example where I do this manually for the first syllables in the music:

<img width="675" alt="Screen Shot 2021-06-11 at 7 53 29 AM" src="https://user-images.githubusercontent.com/3487289/121707545-8543a580-ca8b-11eb-9cdd-14e44486fc4f.png">

`verse@n="1"` is removed, `verse@n="2"` is moved to `verse@n="1"` and `verse@n="3"` is moved to `verse@n="2"`, etc.

```xml
                           <chord xml:id="chord-0000000806973680" dur.ppq="8" dur="4" stem.dir="up">
                              <!--verse xml:id="verse-0000000417535858" n="1" type="verse1">
                                 <label>1.</label>
                                 <syl xml:id="syl-0000001399867897" con="s" wordpos="s">“Come,</syl>
                              </verse-->
                              <verse xml:id="verse-0000001987488969" n="1" type="verse2">
                                 <label>2.</label>
                                 <syl xml:id="syl-0000000821377709" con="s" wordpos="s">“Come,</syl>
                              </verse>
                              <verse xml:id="verse-0000000698257159" n="2" type="verse3">
                                 <label>3.</label>
                                 <syl xml:id="syl-0000001214336788" con="s" wordpos="s">Is</syl>
                              </verse>
                              <verse xml:id="verse-0000000887848760" n="3" type="verse4">
                                 <label>4.</label>
                                 <syl xml:id="syl-0000000688731410" con="s" wordpos="s">Not</syl>
                              </verse>
                              <!--verse xml:id="verse-0000001477605432" n="5" type="verse5">
                                 <label>5.</label>
                                 <syl xml:id="syl-0000000914075213" con="s" wordpos="s">We</syl>
                              </verse-->
                              <!--verse xml:id="verse-0000001043691305" n="6" type="verse6">
                                 <label>6.</label>
                                 <syl xml:id="syl-0000001590517597" con="s" wordpos="s">For</syl>
                              </verse-->
                              <note xml:id="note-0000000397155223" oct="4" pname="c" />
                              <note xml:id="note-0000002027944850" oct="4" pname="e" />
                           </chord>
```

**Comment by samuelbradshaw** [comment]
Changing the `verse@n` value for the verses that remain visible is the hard part. Is there an easy way to do that with XSLT, or does it involve manually looping through each one?

**Comment by craigsapp** [comment]
The basic algorithm would be to use [XPath](https://www.w3schools.com/xml/xpath_syntax.asp) to select all `<verse>` elements in the data.  Then iterate through that list either deleting or renumbering by adjusting `verse@n`.

**Comment by samuelbradshaw** [comment]
It seems that removing or commenting out a verse should cause it to not affect the rendering. I like the idea of modifying how `m_verseCount` works, to not rely on the largest value of `verse@n`, but instead to rely on the number of verses available in the XML.

I looked around a little bit, and couldn't find where `GetVerseCount()` is defined. What file is that in?

**Comment by samuelbradshaw** [comment]
MusicXML files exported from Finale with choruses are encoded with `verse@n` incremented up from the last verse. This causes layout issues with the chorus: 
https://singpraises.net/meta/sheet-music/the-day-dawn-is-breaking

Would changing how the number of verses is calculated fix this chorus issue as well?

**Comment by craigsapp** [comment]
> I don't have a strong opinion on `verse@visible`, but it seems that entirely removing or commenting out a verse should cause it to not affect the rendering.

The last part of the sentence is vague, but I interpret it to mean you want all of the verses to shift up if `verse@n="1"` is commented out?  Definitely not.  The vertical position of lyrics is controlled by `verse@n="#"`, and that must not change.   This is critical for correct layout of lyrics in the general case.  So commenting out a verse is currently behaving as expected in both MusicXML and MEI.

It should be acceptable to add a verovio option called `--verse-collapse` to do this explicitly, which would run a function to analyze verse numbers and drop verses down from higher numbers to fill in empty verse slots starting at `@n="1"`.

A more ambitious option would be one that selects which verses to keep in the rendering (or output to a processed MEI file), such as `--verse-select "1,3-5"`, and when used with `--verse-collapse`, the output `verse@n` would become 1, 2, 3, 4 with 3, 4, 5 moving down to 2, 3, 4,  filling in the missing `n="2"` spot.  

Another thought is that --verse-select "5-3,1" could be used to place the verses in reverse order while at the same time dropping the original verse 2.   A further though would be to use `$` as the highest verse number present in the data, such that `--verse-select "1,3-$"` would remove `verse@n="2"` and keep all other verses.  Similarly, `--verse-select "1-$2"` could be used to select all verses except the last two. 

These two options would allow you to avoid XSLT programming 😉 

@lpugin et al. can comment on the suitability of such options for verse manipulation.  

I think it would be of general usefulness:  Consider the case that @samuelbradshaw has already mentioned: suppose that there are verses displayed at the bottom of the page.   These verses could also be encoded within the music.  Then there could be third related option such as `--verse-extra "auto|none|music|text"` that could select which format for the extra verses should be displayed as: `music` for displaying the extra verses within the music, and suppressing the text verses outside of the music, and `text` for suppressing the extra verses in the music and displaying only the text-formatted verses at the end of the music. `auto` would be the default which would do nothing, so that both the inline and post-music verses are displayed, and `none` would remove both the inline and post-music verses.  (There would need to be a convention or way of encoding the verse number for the text-formatted verses).

**Comment by craigsapp** [comment]
The verses for the chorus need to be "collapsed", and if this is the default expected behavior in MusicXML processing, then it should be done automatically when converting to MEI. (Cite documentation about this if you can find it).

<img width="544" alt="Screen Shot 2021-06-11 at 5 28 48 PM" src="https://user-images.githubusercontent.com/3487289/121759443-8d770180-cada-11eb-83e6-fb657cdc6034.png">

The italicized quarter note is strange...

If you load this MusicXML file into Finale/MuseScore(/Sibelius), are the chorus lyrics displayed properly?  I.e., is the vertical layout lost when exporting to MusicXML?  And are there otherwise layout hints such as `@default-y` being used to control the vertical position of the verses, in particular the chorus lyrics.

**Comment by samuelbradshaw** [comment]
> Another thought is that --verse-select "5-3,1" could be used to place the verses in reverse order while at the same time dropping the original verse 2. A further though would be to use `$` as the highest verse number present in the data, such that `--verse-select "1,3-$"` would remove `verse@n="2"` and keep all other verses. Similarly, `--verse-select "1-$2"` could be used to select all verses except the last two.

At that rate, why not allow repeating verses, too? --verse-select "1, 2, 3, 1, 4"

I like all of these options, as long as it doesn't end up being so complicated that we can't meet the base use case of hiding specified verses. :)

**Comment by craigsapp** [comment]
> I like all of these options, as long as it doesn't end up being so complicated that we can't meet the base use case of hiding and collapsing specified verses. :)

😉 Yes, all of the features need not initially be implemented, but forethought is useful so that the basic implementation can be expanded without "refactorization".

> At that rate, why not allow repeating verses, too? --verse-select "1, 2, 3, 1, 4, 3"

Yes, that would be a useful generalization, although not very commonly used I would suspect:

<img width="1331" alt="Screen Shot 2021-06-11 at 5 48 40 PM" src="https://user-images.githubusercontent.com/3487289/121760011-5f46f100-cadd-11eb-94eb-2801220445f2.png">

**Comment by samuelbradshaw** [comment]
> If you load this MusicXML file into Finale/MuseScore(/Sibelius), are the chorus lyrics displayed properly? I.e., is the vertical layout lost when exporting to MusicXML? And are there otherwise layout hints such as `@default-y` being used to control the vertical position of the verses, in particular the chorus lyrics.

There is vertical positioning information encoded in the MusicXML. MuseScore doesn't handle it well, but Finale handles it very well. In a digital setting, there does need to be some compromise between exact layout and reflowable layout, so I wouldn't expect Verovio to be quite as strict as Finale with the positioning.

MuseScore:
<img width="825" alt="Screen Shot 2021-06-11 at 7 15 40 PM" src="https://user-images.githubusercontent.com/7323052/121760760-99b68b00-cae9-11eb-9202-00d77074f01e.png">

Finale:
<img width="739" alt="Screen Shot 2021-06-11 at 7 15 54 PM" src="https://user-images.githubusercontent.com/7323052/121760765-9d4a1200-cae9-11eb-99ba-41a7315e9bed.png">

Here's a source file:
https://assets.ldscdn.org/fb/66/fb66ca2f5a52392c8c48516cdcd4409ce9e0d9c2/the_day_dawn_is_breaking.mxl

**Comment by lpugin** [comment]
See test suite example lyric-013 for the implementation for the `--lyric-verse-collapse` option
https://www.verovio.org/test-suite.xhtml?cat=lyric
The original problem raised by this issue is now solved with this option.

**Comment by samuelbradshaw** [comment]
Awesome, thank you! This is very helpful!
