### ISSUE TITLE
Multiple accidentals as note children

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#2474]
**Describe the problem**
When there are multiple accidentals encoded in one note, all are actually rendered.

**To Reproduce**
1. Load the data attached
2. Render page X
3. See all encoded accidentals rendered 

**Expected behavior**
It is unclear if this is the desired behavior. 
(Should that even be allowed in MEI?)

**Input data**
```xml
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Multiple accidentals</title>
         </titleStmt>
         <pubStmt>
            <date isodate="2021-11-08">2017-05-09</date>
         </pubStmt>
         <notesStmt>
            <annot>Verovio renders all accidentals within one note.</annot>
         </notesStmt>
      </fileDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp>
                     <staffDef n="1" lines="5" clef.shape="G" clef.line="2" key.sig="0" meter.count="4" meter.unit="4" meter.form="invis" />
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure>
                     <staff n="1">
                        <layer n="1">
                           <note dur="1" oct="4" pname="a">
                              <accid accid="s" />
                              <accid accid="f" />
                              <accid accid="ss" />
                              <accid accid="x" />
                              <accid accid="ff" />
                              <accid accid="tf" />
                              <accid accid="n" />
                           </note>
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

**Screenshots**
![multipleaccids](https://user-images.githubusercontent.com/7693447/140742185-21045795-6db5-4d97-9284-c26a86426172.png)

**Comment by craigsapp** [comment]
> (Should that even be allowed in MEI?)

Not really, since these sorts of cases have no semantic meaning.

It will be confusing to allow such an encoding because `ns` is one accidental (preceded in the measure by a double sharp that is being cancelled), and someone may try to encode it instead as `n` + `s`, which has no meaning (the note cannot be natural and sharp at the same time).  If two accidentals on one note does have meaning, then probably it means there should be two notes: one has a natural and the other has a sharp (but in that case it should be encoded as two notes, each with a different accidental).  Also, verovio is rearranging the order of the accidentals on a single note, and since there is no known meaning, it should not do that.

**Comment by lpugin** [comment]
It looks appropriate to me except maybe for the order. But I am not sure it is worth solving this because am not sure it makes an awful lot of sense.

**Comment by kepper** [comment]
Having discussed this at today's ODD Friday, and we came to the conclusion that yes, it's not recommended but also yes, it should still be allowed, as we can envision situations where we face that in scores. Instead of removing the possibility to have multiple accidentals as direct children (other than being nesting into <choice> etc.), we propose to add a Schematron rule that will just give a warning about this behaviour, so people can still do that if necessary.

**Comment by kepper** [comment]
A new ticket on MEI should be opened (and linked here) so that we can add that Schematron over there…

**Comment by musicEnfanthen** [comment]
There could be use cases in non-tonal, non-diatonic contexts, like Ben Johnston’s _String Quartet No. 5_, see the example here: 
https://www.scoringnotes.com/reviews/microtonal-playback-in-dorico/

**Comment by craigsapp** [comment]
> https://www.scoringnotes.com/reviews/microtonal-playback-in-dorico

I would say that this example is closer to the case of `ns` and `nf` accidentals, since they are not separate accidentals, but rather a compound glyphs to represent a single accidental:

https://www.scoringnotes.com/reviews/microtonal-notation-in-dorico
<img width="114" alt="Screen Shot 2021-11-26 at 6 03 11 PM" src="https://user-images.githubusercontent.com/3487289/143613170-7bb2783c-2d5b-4bbe-975b-340aed4b873d.png">


A related more relevant case that I came across recently was a note with two editorial accidentals above it, separate by a slash.  The meaning was that there are two possible interpretations of the accidental (for two notes that sound at the same time).  Either one of them is sharp or the other is flat (but not both at the same time).   But such a situation may be better handled by a `<choice>` or similar (although the printed edition showed both).  Perhaps a practical implementation of this sort of case is with a choice with hidden accidentals, and then add the two accidentals separated with a slash as a `<dir>` above the notes.

**Comment by musicEnfanthen** [comment]
There is a combination of what is called13°-7° in the listing of microtonals above and a sharp sign in the second violin (m.8) of the Johnston example. And another "tripartite" combination in m. 9 of the viola. Not sure if these would be represented as single glyphs. But yes, agree that it is quite an edge case.
