### ISSUE TITLE
Verovio in iOS app on iOS App Store

### ISSUE THREAD

**Issue by subsonic342** [rism-digital/verovio#2559]
I have noticed that Verovio has been used in a few apps on the iOS App Store:
[NomadPlay](https://www.nomadplay.app/)
[Cantico](https://www.cantico.me/)
[Trala](https://trala.com/)
[Enote](https://enote.com/)

However, none of these apps provide any instructions on how to re-link a custom version of Verovio with their iOS app.

This is straight forward enough on Windows/Linux/Android, just compile a custom Verovio .dll/.so file and replace the original library file. The same can't be said about iOS due to the locked down nature of that operating system.

So as long as we do what @eNote-GmbH is doing, giving Verovio credit and publishing our modifications, **we do not need to provide users a way to re-link a custom version of Verovio with an iOS app?**

It was mentioned in #998 that the reason why Verovio is not available under a more permissive license like MIT/BSD/Etc is because you want to "ensure that modifications and improvements to the library are made available to the community, and also credits to be given". I think companies like @eNote-GmbH would still contribute their improvements to Verovio even if the project was available under MIT/BSD/Etc because we all understand the value of open source and working together.

**Wouldn't it be a good idea to at least license Verovio under the [MPL](https://www.mozilla.org/en-US/MPL/) (alternatively or in addition to the LGPL)?**

Developers would still be [required](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) to publish modifications and give credit to Verovio as desired, but they would not have to provide a way to re-link the library.

**Comment by ahankinson** [comment]
I don’t understand the problem. You want users of App Store apps to be able to link a custom version, but you also note that this is harder due to the locked-down nature of iOS.

What is the LGPL license preventing you from doing?

**Comment by subsonic342** [comment]
> What is the LGPL license preventing you from doing?

Nothing. The LGPL isn't preventing anything. Apple is preventing people from following the LGPL. 

So my question was is it ok to not follow the LGPL (because of Apple) by not providing users a way to re-link a custom version of Verovio with an iOS app?

So @eNote-GmbH does not need to provide a way for me to use their [Enote](https://enote.com/) iOS app with a custom version of Verovio?

**Comment by ahankinson** [comment]
The issue of LGPL and the App Store is widely covered online. Other libraries, such as Qt, are LGPL licensed, and are widely used on App Stores. The best answer seems to be that it's actually fine, although like most things we would need expensive lawyers to figure that out.

If you were a contributing member to this project, we could work together to see if there were other areas of concern you might have and how to address them. However, this seems to be your first issue on GitHub, your account has no other activity, and you provide no details on who you are, or your motivations for bringing this up. 

If you are willing to share more details about yourself, and your motivations, then I think we can continue this discussion. Otherwise, sadly, it seems like you are just trying to cause problems.

@lpugin I'm closing this issue; feel free to open it if you have other thoughts or wishes.

**Comment by AndyDentFree** [comment]
Thanks for the very clear clarification here - I'm currently quoting on an iPad music app and found Verovio and some of the apps linked above. If this project goes ahead will be very happy to make any contributions I can.

I agree entirely with your dismissal of the original poster's opening of this thread. Their point about _people still contributing_ is not born out by my experience. I wrote an XML parser library used in core parts of Steam and they never even acknowledged it. I only found out about it years later in a published interview where they mentioned _making fixes._ My stuff was all MIT licensed.
