### ISSUE TITLE
Repeats not handled correctly in midi and timemap output

### ISSUE THREAD

**Issue by cambiata** [rism-digital/verovio#2615]
**Describe the problem**
When exporting midi or timemap information from a score containing repeats, the additional musical content of the repeats is ignored. Instead, repeat barlines are treated just as if they were ordinary barlines.

Example: The music xml file repersenting the following, with repeats...
![RepeatsXML](https://user-images.githubusercontent.com/217074/152119510-b417a4f9-0f8e-41d7-bc4b-2f501aed3286.png)

...is exported just as if the repeat barlines would be ordinary barlines
![RepeatsMID](https://user-images.githubusercontent.com/217074/152119960-7b977a11-7295-4d11-aa75-8b590fa4aafe.png)

...where the repeat instead should resolved as this:
![RepeatsMID2](https://user-images.githubusercontent.com/217074/152119615-6ffc06ac-e94d-40f1-b53e-8e1e58b605de.png)

**To Reproduce**
1. Load a source file containing repeats
2. Export as midi or timemap
3. Note that the exported files don't include the repeated musical content

**Expected behavior**
The musical content of repeats should be included in the export.
Not that trivial to resolve, I guess, concidering that repeat ending houses ideally should be included too...

**Comment by lpugin** [comment]
Thanks. Duplicate with https://github.com/rism-digital/verovio/issues/235

**Comment by cambiata** [comment]
Ah, thanks!

**Comment by craigsapp** [comment]
I think there is still work to integrate timemaps with expansion lists?

The current view is that the music should be expanded first according to the expansion lists, and then loaded into verovio for MIDI conversion?   I wonder how that works with mutiple `xml:id`s that an expansion may cause...  In theory this should work: expand the score, load into verovio to extract the performance timemap, then load the original score for doing playback with the svg for the score with highlighting.

In the ideal situation, the timemap creating function would take an expansion list as input, and then generate the timemap for the score based on that expansion (maybe the default would be the current behavior where no expansion is done).  In other words, the score would not need to be literally expanded through copy-and-paste of the parts to expand, but rather the iteration through the score to create the timemap would follow the expansion list.

the timemap would contain unique tstamp for seconds (not MEI tstamps), but there could be multiple entries for qstamps in the timemap (one for each repeat).  I.e., the timemap is sorted by real time (performance time) rather than printed score time.

Internally, the indexing would be by qstamp, where there needs to be an array of tstamps (in seconds) for a note on (and off).   This is for when one note is shown in the score, but it played twice in the performance (Minuet da capos would result in some score notes being played three times).
