### ISSUE TITLE
Cue notes should have cue lyrics

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#2625]
When a note is marked as cue note, child elements are expected to have reduced size too. It works for `accid`, and `artic`, but it doesn't work with `syl`, i.e., the font size on lyrics is expected to be reduced.

![cueText](https://user-images.githubusercontent.com/7693447/152951255-ca5dae06-a455-47b0-87af-6046fb7c7866.png)

![image](https://user-images.githubusercontent.com/7693447/152950965-a493447c-ec07-4e2c-bf54-7f8dbe1629ed.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Ein deutsches Requiem (Excerpt)</title>
            <respStmt>
               <persName role="composer">Johannes Brahms</persName>
               <persName role="encoder">Klaus Rettinghaus</persName>
            </respStmt>
         </titleStmt>
         <pubStmt>
            <date isodate="2022-02-08" type="encoding-date">2022-02-08</date>
         </pubStmt>
      </fileDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp>
                     <staffDef n="1" lines="5">
                        <label>Flute</label>
                        <clef shape="G" line="2" />
                        <keySig sig="1f" />
                        <meterSig count="4" unit="4" />
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure n="1">
                     <staff n="1">
                        <layer n="1">
                           <multiRest num="22" />
                        </layer>
                     </staff>
                  </measure>
                  <measure n="23">
                     <staff n="1">
                        <layer n="1">
                           <rest dur="4" cue="true" />
                           <note xml:id="n9vyh2j" dur="2" oct="5" pname="c" cue="true">
                              <verse n="1">
                                 <syl con="s" wordpos="s">denn</syl>
                              </verse>
                           </note>
                           <note xml:id="nqlif06" dur="4" oct="5" pname="c" cue="true">
                              <verse n="1">
                                 <syl con="s" wordpos="s">sie</syl>
                              </verse>
                           </note>
                        </layer>
                        <layer n="2">
                           <mRest />
                        </layer>
                     </staff>
                  </measure>
                  <measure n="24">
                     <staff n="1">
                        <layer n="1">
                           <note xml:id="nykt4hm" dur="4" oct="5" pname="f" cue="true">
                              <verse n="1">
                                 <syl con="d" wordpos="i">sol</syl>
                              </verse>
                           </note>
                           <note xml:id="niwzbya" dur="4" oct="5" pname="e" cue="true" />
                           <note xml:id="noxjmdh" dur="4" oct="5" pname="d" cue="true">
                              <verse n="1">
                                 <syl con="s" wordpos="s">len</syl>
                              </verse>
                           </note>
                           <note xml:id="nz789s3" dur="4" oct="5" pname="e" cue="true">
                              <verse n="1">
                                 <syl con="d" wordpos="i">ge</syl>
                              </verse>
                           </note>
                        </layer>
                        <layer n="2">
                           <mRest />
                        </layer>
                     </staff>
                     <slur startid="#nykt4hm" endid="#niwzbya" curvedir="above" />
                  </measure>
                  <measure n="25">
                     <staff n="1">
                        <layer n="1">
                           <note xml:id="ndl5g0w" dur="4" oct="5" pname="c" cue="true">
                              <verse n="1">
                                 <syl con="d" wordpos="m">trös</syl>
                              </verse>
                           </note>
                           <note xml:id="n1e8nzg" dur="4" oct="4" pname="a" cue="true">
                              <verse n="1">
                                 <syl con="s" wordpos="t">tet</syl>
                              </verse>
                           </note>
                           <note xml:id="nwtm2q3" dur="2" oct="4" pname="f" cue="true">
                              <verse n="1">
                                 <syl con="d" wordpos="i">wer</syl>
                              </verse>
                           </note>
                        </layer>
                        <layer n="2">
                           <mRest />
                        </layer>
                     </staff>
                     <slur startid="#nwtm2q3" endid="#nqmeeg0" curvedir="above" />
                     <tie startid="#nwtm2q3" endid="#n2897jx" />
                  </measure>
                  <measure n="26">
                     <staff n="1">
                        <layer n="1">
                           <note xml:id="n2897jx" dur="2" oct="4" pname="f" cue="true" />
                           <beam>
                              <note dur="8" oct="4" pname="f" cue="true" />
                              <note dur="8" oct="4" pname="d" cue="true" />
                           </beam>
                           <note xml:id="nqmeeg0" dur="4" oct="4" pname="e" cue="true" />
                        </layer>
                        <layer n="2">
                           <mRest />
                        </layer>
                     </staff>
                  </measure>
                  <measure n="27" right="invis">
                     <staff n="1">
                        <layer n="1">
                           <rest dur="4" />
                           <note dur="4" oct="4" pname="a" />
                        </layer>
                        <layer n="1">
                           <note xml:id="n241t59" dur="4" oct="4" pname="f" cue="true" stem.dir="up">
                              <verse n="1">
                                 <syl con="s" wordpos="t">den,</syl>
                              </verse>
                           </note>
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

**Comment by craigsapp** [comment]
I am wondering about a case related to this:  there are cases where there are multiple verses set to the same music.  Sometimes there are more syllables in one verse than another, and sometimes there are cue-sized notes to indicate how to sing the extra syllables.

Obvious these notes are not cue note, but rather cue-sized notes.  Is there a way to differentiate between these two cases in MEI (and does verovio implement this differentiation)?

**Comment by rettinghaus** [comment]
Yeah, this is the same with some [fiorituras](https://en.wikipedia.org/wiki/Fioritura) which are not cue notes nor grace notes. 
I would encode it like `<note fontsize="small" />`, but I'm not sure if the expected behavior then would be to scale down accidentals, articulations and syllables accordingly. Maybe time for another MEI ticket?

**Comment by rettinghaus** [comment]
Again: these are small notes, not cue notes.

**Comment by craigsapp** [comment]
No: those are cue notes (notice the large whole-measure rest in layer 1).  Of course they are some sort of hybrid since obviously they should be sung, but they are notated as if they are cue notes (having a normal sized rest at the same time as cue-sized notes.

**Comment by craigsapp** [comment]
Here is the original sort of thing I was thinking of:

https://kern.humdrum.org/cgi-bin/ksdata?file=erk061.krn&l=users/craig/songs/erk/liederschatz/band1&format=pdf


<img width="1278" alt="Screen Shot 2022-03-11 at 3 12 38 AM" src="https://user-images.githubusercontent.com/3487289/157856908-85133c23-15e8-4af4-803e-8ccbd14351b6.png">

single syllables `kommt` and `kämmt` in the first two verses, but `schaut nur` in the third verse, with the small note added for that verse only.  There is also strange layering (must be related to beaming for syllable grouping), where it is unclear if the notes are cue are not (since the notehead is shared between the voices).

**Comment by craigsapp** [comment]
Are they cue notes now?:

<img width="1018" alt="Screen Shot 2022-03-11 at 3 21 37 AM" src="https://user-images.githubusercontent.com/3487289/157857757-970784cc-6f47-4257-ba8e-04751d107c82.png">

**Comment by samuelbradshaw** [comment]
"O Come, All Ye Faithful" is a common Christmas carol that has this, on the first word. If you scroll down to the page scans, sometimes they use a smaller note, and sometimes they put the note in parentheses: https://hymnary.org/text/o_come_all_ye_faithful_joyful_and_triump

**Comment by craigsapp** [comment]
From the link above notice the use of a quarter note in the lyrics:

<img width="442" alt="Screen Shot 2022-03-12 at 4 36 48 AM" src="https://user-images.githubusercontent.com/3487289/158018211-19941db0-d5c4-4ae9-8c66-8e7c8925dced.png">

Also notice the use of a dashed slur to indicate different syllables counts between verses.

Here is an interesting case related to different language settings:

<img width="220" alt="Screen Shot 2022-03-12 at 4 42 02 AM" src="https://user-images.githubusercontent.com/3487289/158018374-c9e171e0-cc1c-4f45-9296-da308cbdddac.png">



<img width="322" alt="Screen Shot 2022-03-12 at 4 53 39 AM" src="https://user-images.githubusercontent.com/3487289/158018728-e1e49914-bf94-4f6b-b1e6-ae3792db7613.png">


<details>
<summary>
Click to view MEI data for above example
</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-03-12T04:53:45" version="3.10.0-dev-382f16c-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m9inw5r">
    <score xml:id="se8wf3y">
     <scoreDef xml:id="swripr2">
      <staffGrp xml:id="s2z17yj">
       <staffDef xml:id="srxchzy" n="1" scale="80.00%" lines="5">
        <clef xml:id="clef-L2F1" shape="G" line="2" />
        <keySig xml:id="keysig-L3F1" sig="1s" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="sgscifm" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L8F1" dur="4" oct="5" pname="d" cue="true" accid.ges="n">
          <verse xml:id="verse-L8F3" n="1">
           <syl xml:id="syl-L8F3" type="repetition repetition-begin" con="d" wordpos="i">
            <rend xml:id="rkv0pey" fontstyle="italic">Je</rend>
           </syl>
          </verse>
         </note>
        </layer>
        <layer xml:id="layer-L2F1N2" n="2">
         <rest xml:id="rest-L8F2" dur="4" ploc="e" oloc="4" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L11" right="invis">
       <staff xml:id="staff-L11F1N1" n="1">
        <layer xml:id="layer-L11F1N1" n="1">
         <note xml:id="note-L12F1" dots="1" dur="4" oct="5" pname="d" accid.ges="n">
          <verse xml:id="verse-L12F2" n="1">
           <syl xml:id="syl-L12F2" type="repetition" wordpos="t">
            <rend xml:id="r11nze8" fontstyle="italic">sús</rend>
           </syl>
          </verse>
         </note>
         <note xml:id="note-L13F1" dur="8" oct="5" pname="c" accid.ges="n" />
        </layer>
       </staff>
       <slur xml:id="slur-L12F1-L13F1" staff="1" startid="#note-L12F1" endid="#note-L13F1" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>

This example comes very close to lyrics attached to a `<rest>` which ontological fanatics have been preventing in MEI.   In this case the syllable is not small/cue (so independent control of lyrical text size from "cue-like" notes which they attach will be needed).   If cue notes will have small syl automatically, then technically attaching this syllable to a rest is required (since there is not a concept of a cue-sized note to differentiate from true cue notes yet).

Note that this is a small-sized staff for the discant voice (so a small note on a small staff).

This will be an MEI issue since there is a `@cue` attribute to indicate a small note that an instrument should not play (but rather help them come in at the proper time and not otherwise get lost).  But there is no description of a "cue-like" note in MEI (that I can find):
    https://music-encoding.org/guidelines/v4/elements/note.html

`note@cue="true"` should have small lyrical text automatically, but "cue-like" notes should have regular-sized lyrical text by default.

Differentiating between the two categories as "cue" and "small" does not seem great, since in terms of notational syntax, these two types of notes are treated the same (at least I have never seen a case where these two are visually different from each other).  Calling them "small"  notes would imply `note@size` control be added for the cue-like control.   There is a `note@fontsize` already, which seems weird to have but is related to a size control.

Since cue and cue-like notes are graphically identical, perhaps adding three states for `note@cue`:   `true`, `false`, `mixed` or similar is more appropriate.   Or: `regular` (empty state), `cue` and `cue-like`.

A hybrid system for `note@size` will probably be best.  Eventually `note@size` is needed for various repertories.   The main units would be in percentages of the result notes size (or default size for cue/grace).  But there could be two symbolic sizes also allowed in this attribute: `cue` and `grace`.   

The `note@size` attribute would be used for creating cue-like notes as in the above example by specifying `note@size="cue"`.   Regular cue notes for instrumental parts (that indicate notes from other parts that they are not supposed to play themselves) would be indicated as currently with `note@cue="true"`.
