### ISSUE TITLE
Add Python builds for Apple Silicon

### ISSUE THREAD

**Issue by lpugin** [rism-digital/verovio#2663]
It seems that this should be available for python 3.8 onwards.
https://cibuildwheel.readthedocs.io/en/stable/

Not sure what to change in the workflow. @musicEnfanthen ?

**Comment by lpugin** [comment]
I think we also need to adjust things here 
https://github.com/rism-digital/verovio/blob/a85a7b10d4bf3fd7c067a5fa385914ae2f32f99a/.github/workflows/python-ci-wheel.yml#L26-L46

Any ideas what `architecture: x64` means here https://github.com/rism-digital/verovio/blob/a85a7b10d4bf3fd7c067a5fa385914ae2f32f99a/.github/workflows/python-ci-wheel.yml#L31
and why `x86` is excluded here https://github.com/rism-digital/verovio/blob/a85a7b10d4bf3fd7c067a5fa385914ae2f32f99a/.github/workflows/python-ci-wheel.yml#L44

**Comment by musicEnfanthen** [comment]
For the `arm64` configuration: We could try to skip cibuildwheel on python version below 3.8 which does not support Apple Silicon.

So here: 
https://github.com/rism-digital/verovio/blob/a85a7b10d4bf3fd7c067a5fa385914ae2f32f99a/.github/workflows/python-ci-wheel.yml#L89

it should probably read

`CIBW_SKIP: "cp27-* cp37-macosx_arm64" # manylinux2014 not compatible with python 2.7, macosX arm64 not compatible with python < 3.8`

Did not test it, so not sure about the syntax with quotation marks, but took it from here: https://cibuildwheel.readthedocs.io/en/stable/options/#examples_1

If that does not work, because cibuildwheel internally would pass the arm64 config to the build step nonetheless, it could be an option to split up the cibuildwheel step in the gh actions workflow into two steps, one for python 3.7 without arm64, and one for python >= 3.8 with arm64 config.

**Comment by rettinghaus** [comment]
I tested @musicEnfanthen's suggestion [here](https://github.com/rettinghaus/verovio/actions/runs/1883439122) and it seems to work.

**Comment by lpugin** [comment]
Thanks for trying. I can see only four builds for macos, all seem to be for x86_64. E.g., https://github.com/rettinghaus/verovio/runs/5293392197?check_suite_focus=true#step:6

Am I overlooking something? Could you point me to the arm64 build?

**Comment by lpugin** [comment]
I added the `arm64` in the matrix here. 
https://github.com/lpugin/verovio/commit/820fa566517b00292e216c8a41f29bf49d6e62b5

This fails because python-setup does not seem to support arm64.
https://github.com/lpugin/verovio/runs/5299680915?check_suite_focus=true#step:4:13

See
https://github.com/actions/setup-python/issues/108#issuecomment-656621597

Can we cross-compile the `arm64` wheel from a `x64` machine? Or is there a way to install Python differently?

**Comment by rettinghaus** [comment]
With [setup-python](https://github.com/actions/setup-python) you only can install the x64 build, see https://github.com/actions/python-versions/releases
Also, as it stands, there are currently no plans to support M1 environments in GitHub actions. 
And I don't think we can cross-compile to `arm64` on `x64`, only the other way round with Rosetta 2.

**Comment by lpugin** [comment]
Cross-compiling looks possible https://cibuildwheel.readthedocs.io/en/latest/faq/#apple-silicon
I am looking at it.

**Comment by rettinghaus** [comment]
O yes, at least we have to `CIBW_TEST_SKIP: *_arm64`.

**Comment by lpugin** [comment]
Building works https://github.com/lpugin/verovio/runs/5300429546?check_suite_focus=true#step:8:11

I still need to fix the testing which pulls all the wheels. That is different from the `CIBW_TEST_SKIP`

**Comment by musicEnfanthen** [comment]
@lpugin Can you try the following change:
```

      - name: Install from wheel on Unix
        if: always() && runner.os != 'Windows'
        working-directory: wheelhouse
        run: python -m pip install ./*.whl  ## change to  -->  ./*_x86_64.whl
```

This should exclude the arm64 wheels from the pip install check, since they are not supported on the x64 runners (as you said, at the moment there aren't any arm64 compatible runners in GH actions). At the same time, x64 wheels should pass this check on ubuntu and macosx.

Please be aware that the arm64 wheel needs to be considered "untested" then.

**Comment by lpugin** [comment]
Thanks. This is what I did and it seems to work https://github.com/lpugin/verovio/runs/5301787587?check_suite_focus=true

**Comment by musicEnfanthen** [comment]
Perfect :)

**Comment by lpugin** [comment]
https://test.pypi.org/project/verovio/3.10.0.dev0/#files
