### ISSUE TITLE
General questions: bar lines and lyrics and Humdrum filters

### ISSUE THREAD

**Issue by WolfgangDrescher** [rism-digital/verovio#2690]
I'm not sure if here is the best way to ask general questions about Verovio and Humdrum since I have not a specific issue or feature request. Is there any other community server (e.g. Slack)? Or maybe it could be a good idea to enable GitHub Discussions so Verovio users can get in touch with each other.
Since I am not aware of any other communication channels, I would like to ask a few questions here anyway.

## Verovio

1. Is it possible to display bar lines between staffs? If so, is it also possible with Humdrum and the `kern2mens` filter active?

<img width="1318" alt="Bildschirmfoto 2022-03-04 um 15 38 18" src="https://user-images.githubusercontent.com/865594/156785014-7814334b-0834-473c-bcd5-b1eaaeb1e3f5.png">

2. Is it possible to display lyrics in a different style (e.g. italic) when I want to show semantically that the lyrics are not by the composer himself? If so, can this be encoded in Humdrum `.krn` files?

<img width="1305" alt="Bildschirmfoto 2022-03-04 um 15 54 22" src="https://user-images.githubusercontent.com/865594/156786581-67895767-e279-41a3-af4d-74e77728a9f4.png">

3. Im not sure if this is Verovio or Humdrum related. When i use `!!!filter: kern2mens` notes are not aligned vertically to each other. The beginnings of each "bar" are always in sync (green), but within a "bar" notes do not match above the other staffs (red). Is there a way to get this in sync?

<img width="981" alt="Bildschirmfoto 2022-03-04 um 16 18 07" src="https://user-images.githubusercontent.com/865594/156791561-b5a89e16-00ca-4e1f-bb6b-dc39dfcd6489.png">

## Humdrum

Please feel free to redirect me to the humdrum-tools GitHub issues or any other place if these questions don't belong here.

4. Is there a filter in Humdrum to change the clef for a single spine? Or would I have to string replace the `*clefXX` by hand in the score data string?

5. Is it possible in Humdrum to encode longer note durations than value `0`? This would be especially useful for pauses at the beginning of Renaissance pieces.

<img width="364" alt="Bildschirmfoto 2022-03-04 um 16 06 24" src="https://user-images.githubusercontent.com/865594/156788046-7986666c-6eec-4b34-ba79-bfff90640abc.png">

6. Is it possible to set colors for different `cint` filters? I found `!!!RDF**kern: @= matched note, color="#ff0000"` but this always changes the color for all `cint` filters. I would like to show multiple `cint` filters at once and show them each in a different color. Something like:

```
!!!filter: cint -O --search "6 2 6" --color #ff0000
!!!filter: cint -O --search "3 2 3" --color #00ff00
```

**Comment by craigsapp** [comment]
> Please feel free to redirect me to the humdrum-tools GitHub issues or any other place if these questions don't belong here.

Yes, the best place for Humdrum + Verovio questions is probably in the VHV [issues](https://github.com/humdrum-tools/verovio-humdrum-viewer/issues) and I can reroute or suggest rerouting from there to other locations.  Humdrum questions of a general nature can be asked in the [**HUG](https://groups.google.com/g/starstarhug) (Humdrum User Group).

For the last group of questions (4 5 & 6):

> Is there a filter in Humdrum to change the clef for a single spine? Or would I have to string replace the *clefXX by hand in the score data string?

Yes, I use the [shed](https://doc.verovio.humdrum.org/filter/shed) tool/filter for doing that.   "shed" means "Humdrum sed" (with the `h` interposed to make it easier to pronounce.  [sed](https://en.wikipedia.org/wiki/Sed) stands for "stream editor".   The shed version adds knowledge of Humdrum file structure, such as spines and data versus interpretations, etc.

Here is an example:

<img width="220" alt="Screen Shot 2022-03-04 at 8 21 38 AM" src="https://user-images.githubusercontent.com/3487289/156800328-a9493b98-0ad5-4b25-87fa-bd90804feccf.png">

```tsv
**kern	**kern
*clefF1	*clefC3
=	=
1F	1c
=	=
*-	*-
```

This filter can be used to change the clef in the first spine to a regular bass clef:

```
shed -s 1 -e s/clefF1/clefF4/I
```

The options are:

* `-s 1`: only process the first spine
* `-e s/clefF1/clefF4/I` is the regular Expression search and replace.  `s` means substitute `clefF1` for `clefF4`, but only on interpretation lines (`/I`) and not on other line types such as data (for notes and rests).

There are two ways of using filters in VHV:

(1) You can add a line such as:

```
!!!filter: shed -s 1 -e s/clefF1/clefF4
```

anywhere in the contents to apply the filter before rendering in VHV:

<img width="830" alt="Screen Shot 2022-03-04 at 8 43 10 AM" src="https://user-images.githubusercontent.com/3487289/156804219-25d77ef4-c2cb-4b5e-9730-a9f377ac883e.png">

To make the filter application permanent and show the result in the text editor, type `alt-c` (windows) or `option-c` (MacOS) to "compile" the filter(s):

<img width="819" alt="Screen Shot 2022-03-04 at 8 43 20 AM" src="https://user-images.githubusercontent.com/3487289/156804358-a88d6ac3-e83d-4564-8f3f-6f114449a7d6.png">

(2) There is a filter panel in the toolbar on the top right, where filters can be typed in:

<img width="804" alt="Screen Shot 2022-03-04 at 9 31 49 AM" src="https://user-images.githubusercontent.com/3487289/156812928-fe89142e-bafa-4457-ba0a-765ee684336f.png">


Then press the funnel icon at the right of the text input box (highlighted in yellow above) to temporarily apply the filter to the score.  You can then press the `+` on the right side of the funnel icon to make the filter be applied permanently to the data.

If you have a lot of files that need changing, you can download [humlib](https://github.com/craigsapp/humlib) and compile in the terminal (humlib is a collection of Humdrum tools that work both in verovio/VHV and on the command-line).  The use a bash for-loop such as:

```bash
mkdir output
for i in *.krn
do
     echo processing file $i
     shed -s 1 -e "s/clefF1/clefF4/I" $i > output/$i
done
```

Then the filtered files are in the `output` directory (which you can review and then overwrite the original files as needed).

---------------------------

Not knowing the purpose of such change, I will guess that you want to convert C-clefs in mensural music into bass/treble that are easier for modern musicians to read :wink:.  

Firstly, here is the `shed` filter that I use for this purpose:

```
shed -e "s/^clefC[12]/clefG2/I; s/^clefC[34]/clefGv2/I; s/^clefC5/clefF4/I; s/^clefF[35]/clefF4/I; s/^clefG[13]/clefG2/I";
```

Which in English means: convert C1 and C2 clefs to treble clef, C3 and C4 clefs to vocal tenor clef, C5, F3, F5 to bass clef, and G1 and G2 to treble clef.

However, there is also a more sophisticated system for doing such things, using the [modori](https://doc.verovio.humdrum.org/filter/modori) filter/tool (I see that it is not documented yet, so I should do that...).   This is useful if you are encoding your own scores and want both modern and original style clefs encoded in the scores, allowing a convenient switch between the two.

`modori` means "MODern/ORIginal" and is used to switch between modern style notation and original style notation, where clefs, key signatures and time signatures/mensural signs are changed in the notation.

Here is an example usage for modori:

<img width="578" alt="Screen Shot 2022-03-04 at 8 59 55 AM" src="https://user-images.githubusercontent.com/3487289/156806691-cb79dc9a-34f2-4e01-90db-51e9ebec3a61.png">

Notice that the modern clefs are being shown, and the "original" clefs have an `o` prefix.   To display the original clefs, use the `modori -o` filter:

<img width="780" alt="Screen Shot 2022-03-04 at 9 01 32 AM" src="https://user-images.githubusercontent.com/3487289/156806970-8e35b09d-2ef4-4f98-95f3-7c272d4bd5e4.png">

The data can be encoding with the opposite view, showing the original clefs and then specifying what the modern clefs should be:

<img width="582" alt="Screen Shot 2022-03-04 at 9 02 50 AM" src="https://user-images.githubusercontent.com/3487289/156807291-60a54df0-1a59-4d1f-9a69-23df74fa25de.png">

And then use the `modori -m` option to display in modern style:

<img width="776" alt="Screen Shot 2022-03-04 at 9 03 23 AM" src="https://user-images.githubusercontent.com/3487289/156807473-3a0b3a88-2d88-4fc3-afdf-3b9445ad8a0f.png">

where `*mclefG2` is the modern clef (and `*clefC3` is inferred to be the "original" clef).

-----------------------------------
---------------------------------

Is it possible in Humdrum to encode longer note durations than value 0? This would be especially useful for pauses at the beginning of Renaissance pieces.

Yes: `0` means a breve (double whole note), `00` means a long (quadruple whole note), and `000` means a maxima (octuple whole note).

There is also an extended rhythmic syntax that cannot be processed by the original Humdrum tools (but can with Humdrum Extras and humlib based tools/filters):

`1%2` is equivalent to `0`, where `1%2` means that 1/2 of a breve is a whole note.  It is better to look at the reciprocal: 2/1, which means that there are two whole notes in the breve.   Similarly `4%1` is a generalized meaning of `4`, meaning that a quarter note is 1/4th of a whole note.

Cases where such extended rhythmic notation is needed in early music would be for the triplet whole note: `3%2` (2/3rds of a whole note) and triplet breve: `3%4` (4/3rds of a whole note).

---------------------------------

> Is it possible to set colors for different cint filters? I found !!!RDF**kern: @= matched note, color="#ff0000" but this always changes the color for all cint filters. I would like to show multiple cint filters at once and show them each in a different color.

It is possible, but not convenient at the moment.   I can add a color option to cint (do a feature request for that in the VHV issues, although this will be implemented inside of the humlib repository, but I check the issues there less often). 

The default marker for coloring notes is `@` in the cint tool/filter.  And the default color for highlighting is red.

To make it work currently:

```
!!!filter: cint -O --search "6 2 6"
!!!filter: cint -O --search "3 2 3" -N Z
```

This will add two lines to the output data:

```
!!!RDF**kern: @ = matched note
!!!RDF**kern: Z = matched note
```

which you can then change by hand (or with shed)

```
!!!RDF**kern: @ = matched note
!!!RDF**kern: Z = matched note, color=limegreen
```

There is a general problem that you will likely encounter:  Only one color can be applied to a note (when passing through MEI and rendering with verovio).   In the future I plan to add SVG markup to the [Humdrum Notation Plugin](https://plugin.humdrum.org) which is a low-level front-end to verovio for displaying Humdrum files (VHV uses this to interface with verovio, for example).  For example, circling notes with different colors and diameters would be useful.  Another idea would be to notice that there are two (or more) color markers on a note in Humdrum, and then calculate an interpolated third color to indicate an intersection (such as markers for blue and red which display purple when they are both present on a note).

**Comment by craigsapp** [comment]
> Is it possible to display bar lines between staffs?

It is not possible in verovio (unless it slipped by me), and I do not think it is accommodated in MEI yet (and I do not like such notation :-).    This is called [Mensurstrich](https://en.wikipedia.org/wiki/Mensurstrich).

One problem with this sort of barline style is that in modern scores it is not typical for barlines to be entering into the vocal text.   A secondary problem is that it takes too much time to calculate the duration of the pieces of a note that crosses a barline.

For future discussion, there is a related barring style exampled in [CMM 106](http://www.corpusmusicae.com/cmm/cmm_cc106.htm) that would eventually be useful to has as an alternate barring style in MEI/verovio:

<img width="864" alt="Screen Shot 2022-03-04 at 9 51 02 AM" src="https://user-images.githubusercontent.com/3487289/156815697-d019e771-ba53-4da0-8152-2a49bc3ccd81.png">

This is a hybrid between modern barring and Mensurstrich.  I still don't like it, but  I like it better than Mensurstrich, since the barlines are not getting in the way of the vocal text.

I convert the CMM 106 scores to fully modern barring style since it is not currently possible in verovio to do otherwise:

http://verovio.humdrum.org/?file=gaspar/Gas0101a-Missa_Ave_regina_celorum-Kyrie.krn

<img width="953" alt="Screen Shot 2022-03-04 at 9 54 54 AM" src="https://user-images.githubusercontent.com/3487289/156816304-7d3f3717-a2c3-477a-9ac2-9316e506fc25.png">

Note that I have a filter `tie -m` (merge tied notes) that gets you half-way to the CMM 106 style (but this is very confusing since you cannot tell which notes are tied over the barlines, although I am thinking of adding an automatic invisible style to tied-over barlines.  (And I could currently hack the SVG output from verovio if I really needed this display style now):

<img width="976" alt="Screen Shot 2022-03-04 at 10 09 07 AM" src="https://user-images.githubusercontent.com/3487289/156818417-117316b5-a530-4a68-9745-77b7221b4e3b.png">

**Comment by craigsapp** [comment]
> Or maybe it could be a good idea to enable GitHub Discussions so Verovio users can get in touch with each other.

That seems like a good idea.  That would allow verovio newbies in particular to ask questions as well as see previous questions/answers.   And it can also be used for distilling vague ideas into specific issues.

I have tried this in another repository, but I am annoyed that it makes it harder to find a previous post (e.g., was it in issues, or in discussions?).  The verovio issues is more active with non-questions, so I think it would work well to have issues for code-base related things, and discussions for user-based things.

**Comment by craigsapp** [comment]
> Is it possible to display lyrics in a different style (e.g. italic) when I want to show semantically that the lyrics are not by the composer himself? If so, can this be encoded in Humdrum .krn files?

Yes, what you want is the `*ij` and `*Xij` interpretation pair:

<img width="1335" alt="Screen Shot 2022-03-04 at 10 24 47 AM" src="https://user-images.githubusercontent.com/3487289/156820489-6b3503f4-3a34-48e2-96cc-79275c9796b8.png">

I do not have a method of only showing the `ij` rather than the repeated text (I only have editions where the `ij` text was added to the score, since a fully diplomatic rendering was not desired.

There is also `*edit` and `*Xedit` ("editorial text") which is similar to `*ij`, but the meaning is that the text underlay was not specified in the original score and was assigned by a modern editor:

<img width="1338" alt="Screen Shot 2022-03-04 at 10 29 02 AM" src="https://user-images.githubusercontent.com/3487289/156821060-87af7a1b-2471-447a-b586-f19127bde1e1.png">

And finally, if you want to indicate that the lyrics are in an italic style, but you do not want to (or know) a specific reason for the italics, use `*italic` and `*Xitalic`:

<img width="1343" alt="Screen Shot 2022-03-04 at 10 33 41 AM" src="https://user-images.githubusercontent.com/3487289/156821852-6b1c9129-b95a-4f5d-953d-b5c3c69bde6e.png">

(I can add additional semantic reasons beyond `*ij` and `*edit` as needed).

**Comment by craigsapp** [comment]
> Im not sure if this is Verovio or Humdrum related. When i use !!!filter: kern2mens notes are not aligned vertically to each other. The beginnings of each "bar" are always in sync (green), but within a "bar" notes do not match above the other staffs (red). Is there a way to get this in sync?

This is likely a but, which in turn is most likely because `kern2mens` is not very advanced.  However, music in C and Cut-C should not have problems like this.

This would be a good issue to add to the [VHV issues](https://github.com/humdrum-tools/verovio-humdrum-viewer/issues). (Also give the Humdrum encoding of that system of music for me to debug what is going wrong).

In case you don't know how to do it, here is how you can add Humdrum content to an issue page:

````
```tsv
**kern
1c
*-
```
````

`tsv` stands for Tab-Separated Values (which is a known format for Markdown, although the colorization is nearly nothing (just displays in blue).

**Comment by WolfgangDrescher** [comment]
Very interesting. Thanks a lot @craigsapp for the detailed explanations! This helps a lot for my little project where I get to know Humdrum better with Lassus Geistliche Psalmen :-)

> Yes, the best place for Humdrum + Verovio questions is probably in the VHV [issues](https://github.com/humdrum-tools/verovio-humdrum-viewer/issues) and I can reroute or suggest rerouting from there to other locations. Humdrum questions of a general nature can be asked in the [**HUG](https://groups.google.com/g/starstarhug) (Humdrum User Group).

Perfect I will ask there next time and join **HUG.

> Yes: 0 means a breve (double whole note), 00 means a long (quadruple whole note), and 000 means a maxima (octuple whole note).

Works as expected with`kern2mens` thank you. But I guess in modern notation there should be a break in the second bar instead of an empty bar? Maybe this is an edge case that could be handled. I can open an issue in the VHV repository if needed. Maybe this is even related to the `tie -m` problem that you mentioned. [Check the source here](https://verovio.humdrum.org/?file=https://raw.githubusercontent.com/WolfgangDrescher/lassus-geistliche-psalmen/07acddbc759e9e7c7c396bb5bc4370add0752c71/kern/01-beatus-vir.krn).

<img width="1140" alt="Bildschirmfoto 2022-03-04 um 22 27 44" src="https://user-images.githubusercontent.com/865594/156844118-cd67c1c5-56d9-416a-954b-30e67cfc784a.png">

> Note that I have a filter tie -m (merge tied notes) that gets you half-way to the CMM 106 style (but this is very confusing since you cannot tell which notes are tied over the barlines, although I am thinking of adding an automatic invisible style to tied-over barlines. (And I could currently hack the SVG output from verovio if I really needed this display style now):

I achieved it simply by using a null token in the following bar after the "tied" note. `0g \n = \n .` vs `[1g \n = \n 1g]` with the`tie -m` filter.

<img width="888" alt="Bildschirmfoto 2022-03-04 um 22 47 28" src="https://user-images.githubusercontent.com/865594/156846337-30c2d7cf-2725-4ef9-b90c-b8f8daf40282.png">

> Yes, what you want is the *ij and *Xij interpretation pair

Im do not unterstand how to use `*ij` and `*edit` semantically correct. See [this source](https://verovio.humdrum.org/?file=https://raw.githubusercontent.com/WolfgangDrescher/lassus-geistliche-psalmen/07acddbc759e9e7c7c396bb5bc4370add0752c71/kern/02-quare-fremuerunt-gentes.krn) (still WIP and early stage). Bassus in bar 19-20 would be `*ij` since I can repeat "thun eitel ding" perfectly on the four notes, while Cantus in bar 4-8 would be `*edit` since the composer gives us "ij" but the editor has to decide how the text "Warumb empören sich die Haiden" is effectively distributed on the following notes. Or is there another semantic expression for both of them combined, since in my case it is marked as `*ij` by the composer but at the same time it is as well `*edit`?

One more question about performance. Currently every time I add a new filter to the score dynamically I just prepend the score string with the given filter(s). Then I use `loadData()` in JavaScript to reload the score with the filters applied. It seemes to me that VHV is much faster with dynamic filters or string manipulation than my own setup. Is there a better way than what I am doing or is the improved performance on VHV because of the service worker?

---

> > Or maybe it could be a good idea to enable GitHub Discussions so Verovio users can get in touch with each other.
> 
> That seems like a good idea. That would allow verovio newbies in particular to ask questions as well as see previous questions/answers. And it can also be used for distilling vague ideas into specific issues.
> 
> I have tried this in another repository, but I am annoyed that it makes it harder to find a previous post (e.g., was it in issues, or in discussions?). The verovio issues is more active with non-questions, so I think it would work well to have issues for code-base related things, and discussions for user-based things.

I will ping @lpugin so he can decide if GitHub Discussions would be beneficial for the verovio repository.

**Comment by ahankinson** [comment]
FYI, there is a Verovio Channel in the MEI Slack if you want to use that to get in touch with, and ask about, Verovio features.

https://music-encoding.org/community/community-contacts.html

**Comment by WolfgangDrescher** [comment]
Thank you for the link @ahankinson.

**Comment by craigsapp** [comment]
Looking at the code, I see that the marker was being hardwired to only be `@` (I was probably thinking about adding the code, but probably never got around to implementing it).

The humlib version of cint now can change the marker.  (There is a humextra version which was ported to humlib in 2017, but that one will eventually be retired and will not be updated).

In general I have been avoiding Unicode because Windows and Linux do not use Unicode character encoding in the operating systems, but I have allowed Unicode for RDF markers with the "-N" option.   They are working in MacOS and on the Web, at least:

<img width="995" alt="Screen Shot 2022-03-16 at 3 46 03 PM" src="https://user-images.githubusercontent.com/3487289/158704029-73d4d1ba-c03d-49a4-ba78-fe32361c5ff0.png">

Compiling the filters in VHV:

<img width="995" alt="Screen Shot 2022-03-16 at 3 50 26 PM" src="https://user-images.githubusercontent.com/3487289/158704087-0c84d71d-b4f0-49df-be8e-4e7ddb102d67.png">

Notice that there is a `--color` option now for the humlib version if `cint`, so no hand-editing is needed to use multiple colors for different searches.

**Comment by WolfgangDrescher** [comment]
Very nice, thank you! Will this automatically be deployed in the JS toolkit with the next Verovio release?

**Comment by craigsapp** [comment]
If @lpugin warns me that a new release is about to come out :-).  Usually I wait to merge until after a release so that there is time to evaluate for any problems, but I can merge the humdrum-to-MEI importer at any time when it is necessary.

**Comment by lpugin** [comment]
> If @lpugin warns me that a new release is about to come out :-)

Will do
