### ISSUE TITLE
renderToTimemap wrongly renders grace notes in the middle of a mesure

### ISSUE THREAD

**Issue by leguye** [rism-digital/verovio#2824]
**Describe the problem**
When using the `toolkit.renderToTimemap()` method, for grace notes contained in a given measure, their ids are included in the `on` and `off` arrays of first TimeMapEntry of the measure. Does the fact that a note is in both arrays make sense?

So that, these grace notes have unexpected onsets (ie: qstamp). Grace notes could also be simply removed from the timemap, as their exact onset is something debattable.

**To Reproduce**
1. Load the given input data
2. Render the timemap with `toolkit.renderToTimemap()` (js code)
3. The first TimeMapEntry of the measure rendered (grace notes ids: 'nlayvmi', 'nwdazat'):

```js
{
  off:(2) ['nlayvmi', 'nwdazat']
  on:(3) ['nlayvmi', 'nwdazat', 'nkt395u']
  qstamp:0
  restsOn:(1) ['rqxzqd']
  tempo:'120.000000'
  tstamp:0
}
```

**Expected behavior**
- ids should be only in one array at a time at 'correct' onset.
- grace notes ids should not be present (?)

**Input data**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Andante amoroso</title>
            <title type="subordinate">2</title>
            <respStmt>
               <persName role="composer">Wolfgang Amadeus Mozart</persName>
            </respStmt>
         </titleStmt>
         <pubStmt><date isodate="2022-04-26" type="encoding-date">2022-04-26</date>
         </pubStmt>
      </fileDesc>
      <encodingDesc xml:id="encodingdesc-7hf7kk">
         <appInfo xml:id="appinfo-tbwrq">
            <application xml:id="application-iat1ux" isodate="2022-04-26T17:54:59" version="3.10.0-dev-9e544c1">
               <name xml:id="name-uxw6hv">Verovio</name>
               <p xml:id="p-kpteqo">Transcoded from MusicXML</p>
            </application>
         </appInfo>
      </encodingDesc>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="moenu8h">
            <score xml:id="sjnyeta">
               <scoreDef xml:id="s9s136v">
                  <pgHead xml:id="poey7mv">
                     <rend xml:id="rfw81ud" halign="right" valign="bottom">S. #</rend>
                     <rend xml:id="riliw2o" halign="center" valign="top">- # -</rend>
                  </pgHead>
                  <staffGrp xml:id="s5fc17q">
                     <staffGrp xml:id="P1" bar.thru="true">
                        <instrDef xml:id="iuwfiju" midi.channel="0" midi.instrnum="0" midi.volume="78.00%" />
                        <staffDef xml:id="s1c6u68" n="1" lines="5" ppq="4">
                           <clef xml:id="c2lui38" shape="G" line="2" />
                           <keySig xml:id="ky0im1t" sig="3f" />
                           <meterSig xml:id="mgbhsrp" count="3" unit="8" />
                        </staffDef>
                        <staffDef xml:id="s7axagi" n="2" lines="5" ppq="4">
                           <clef xml:id="c7jv1bs" shape="G" line="2" />
                           <keySig xml:id="komye2z" sig="3f" />
                           <meterSig xml:id="mc727n8" count="3" unit="8" />
                        </staffDef>
                        <grpSym xml:id="gs9og2g" symbol="brace" />
                     </staffGrp>
                  </staffGrp>
               </scoreDef>
               <section xml:id="sr2ircr">
                  <measure xml:id="mdj27bw" right="end" n="1">
                     <staff xml:id="syxb6jp" n="1">
                        <layer xml:id="lwcvhms" n="1">
                           <rest xml:id="rqxzqd" dur.ppq="2" dur="8" />
                           <note xml:id="nlayvmi" dur="16" oct="5" pname="a" grace="acc" stem.dir="up" accid="n" />
                           <beam xml:id="b1z6u2j">
                              <note xml:id="ntrgh7l" dur.ppq="2" dur="8" oct="5" pname="b" stem.dir="down" accid.ges="f" />
                              <note xml:id="nwdazat" dur="16" oct="5" pname="a" grace="acc" stem.dir="up" />
                              <note xml:id="n38pe5o" dur.ppq="2" dur="8" oct="5" pname="b" stem.dir="down" accid.ges="f" />
                           </beam>
                        </layer>
                     </staff>
                     <staff xml:id="sq830y9" n="2">
                        <layer xml:id="l45o8rr" n="5">
                           <beam xml:id="baw7dbt">
                              <note xml:id="nkt395u" dur.ppq="1" dur="16" oct="4" pname="e" stem.dir="up" accid.ges="f" />
                              <note xml:id="n8u5ijx" dur.ppq="1" dur="16" oct="4" pname="g" stem.dir="up" />
                              <note xml:id="nig2enl" dur.ppq="1" dur="16" oct="4" pname="b" stem.dir="up" accid.ges="f" />
                              <note xml:id="nl17q75" dur.ppq="1" dur="16" oct="4" pname="g" stem.dir="up" />
                              <note xml:id="nb76tqh" dur.ppq="1" dur="16" oct="4" pname="e" stem.dir="up" accid.ges="f" />
                              <note xml:id="nhdobo3" dur.ppq="1" dur="16" oct="4" pname="g" stem.dir="up" />
                           </beam>
                        </layer>
                     </staff>
                     <slur xml:id="sr58ldw" startid="#nkt395u" endid="#nhdobo3" curvedir="below" />
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

**Verovio information**
 - Version of Verovio [e.g. develop, 3.9.0 (aec270747)]

**Environment information (as appropriate)**
 - Ubuntu 20.04.3 LTS
 - Node.js (v16.13.2)

**Screenshots**
![grace-note-timemap](https://user-images.githubusercontent.com/6638032/165544382-ca5637fc-6e8c-426f-8a6a-ef63459ec56d.png)

**Comment by craigsapp** [comment]
> Does the fact that a note is in both arrays make sense?

This is problematic unless the `on` list is processed first, and then the `off` one:

```javascript
{
  off:(2) ['nlayvmi', 'nwdazat']
  on:(3) ['nlayvmi', 'nwdazat', 'nkt395u']
  qstamp:0
  restsOn:(1) ['rqxzqd']
  tempo:'120.000000'
  tstamp:0
}
```

Otherwise, the grace note (highlighting) would never be turned off.

A related problem is that the "score time" of the grace notes are being used (since that they have zero duration).   When I play the MEI data in verovio, the grace notes are being treated (as I expect) as 16th notes&mdash;so I suppose this means that the grace note performance times are not incorporated into the timemap?

At one point grace notes were not added to the timemap (with one reason being that they were not rendered to MIDI).  Since grace notes have a score time of 0 and the purpose of the timemap is to highlight notes in an SVG image during MIDI playback, I am wondering why grace notes are in the timemap if they are stored with 0 duration?   And if they are placed in the timemap, then their MIDI performance times should be used so that highlighting of grace notes can be done when they are sounding in the MIDI performance (but that might require the timemap to be sorted, since some grace notes are inserted into the MIDI file with a negative time offset and sorted before writing the MIDI file).

-----------------------

Mozart wrote them differently (as 8th notes with a slash through the stem):

<img width="151" alt="Screen Shot 2022-04-27 at 9 07 00 AM" src="https://user-images.githubusercontent.com/3487289/165565409-890169e6-2f65-4a7d-acc6-57e72b8c1db9.png">

page 16, measure 17 of 
https://s9.imslp.org/files/imglnks/usimg/9/98/IMSLP294539-PMLP01830-Mozart_-_Sonatas_K279-284_-autograph-.pdf

-------------------------------------

The NMA IX/25/1: KV 281 (189f)
<img width="243" alt="Screen Shot 2022-04-27 at 9 20 21 AM" src="https://user-images.githubusercontent.com/3487289/165565636-06003964-afc5-4adf-9e46-ac05dd67bf23.png">
page 6 of https://imslp.eu/files/imglnks/euimg/3/39/IMSLP424701-PMLP01834-nma_196_26_39.pdf


-----------------------

Mozarts Werke, Serie XX:Sonaten und phantasien für das pianoforte, No.3 (pp.2-11 (20-29))Leipzig: Breitkopf & Härtel, 1878. Plate W.A.M. 281 (Alte Mozart-Ausgabe)

<img width="239" alt="Screen Shot 2022-04-27 at 9 25 46 AM" src="https://user-images.githubusercontent.com/3487289/165566785-f928f990-428c-4ab0-8e63-f18f4e2fafbf.png">

Page 5 of  https://s9.imslp.org/files/imglnks/usimg/c/cf/IMSLP56312-PMLP01834-Mozart_Werke_Breitkopf_Serie_20_KV281.pdf

---------------------

Sonaten für Klavier zu zwei Händen (pp.28-44)
Leipzig: C.F. Peters, n.d.(ca.1938). Plate 10817-10818.

<img width="176" alt="Screen Shot 2022-04-27 at 10 54 47 AM" src="https://user-images.githubusercontent.com/3487289/165589387-750df214-61af-4883-9ab8-ed78ddfd76f0.png">

Page 7 of https://s9.imslp.org/files/imglnks/usimg/e/e9/IMSLP70201-PMLP01834-KV_281.pdf


Examples from https://imslp.org/wiki/Piano_Sonata_No.3_in_B-flat_major,_K.281/189f_(Mozart,_Wolfgang_Amadeus)

Looking at the variants, it looks like it should be a short note played on the beat.  Mozart's original notation using the slash is now typically played before the beat and without slash is on the beat, so that is why other editions change it.  Performance should probably be closest to the Alte Mozart-Ausgabe edition: played approximately as a 32nd note on the beat.

Why is the NMA using 16th-note grace notes here @ndubo?
