### ISSUE TITLE
Additional value "measure" for --breaks

### ISSUE THREAD

**Issue by wergo** [rism-digital/verovio#2975]
The option `breaks`currently supports `"none"`, `"auto"`, `"encoded"`, `"line"`, and `"smart"`, each serving a different purpose of chopping the notation in different ways.

I suggest to add a new value `"measure"` for the option `breaks` that chops the music content measure-wise (thus one measure per page). This would be an important feature for measure-wise encoding applications.

**Comment by lpugin** [comment]
What do you mean by measure-wise encoding applications? I am not against the idea, of course, but I would be interested to know more about what you have in mind. One reason is that I am a little bit unsure about the visual result with content varying in width. Do you expect a measure to be justified in order to fill the page?

Another question would be what to expect with pickup measures. What do you have in mind for this?

**Comment by wergo** [comment]
We are working on showing a zone of a source edition together with the encoding for easing transcription and allowing micro-trasks to be distributed to users. 

This is an excerpt from a file by the Beethoven in the House project: 

<img width="1512" alt="Bildschirmfoto 2022-07-21 um 17 48 34" src="https://user-images.githubusercontent.com/45632600/180257820-d04e7ed3-32aa-4705-bb87-3c9b144663de.png">

**Comment by wergo** [comment]
Pickup measures, incomplete measures (`@metcon="false"` or `@right="invis"`) would just be treated as one measure, ignoring their incompleteness.

**Comment by lpugin** [comment]
What about using the toolkit `select` method? You can easily render a single measure. Wouldn't this do the job?

**Comment by wergo** [comment]
Yes, that would do the job, but would require more UI design decisions. From a UI perspective it would be somewhat easier to have such an option value. Let's talk about it next week in person. Thanks!
