### ISSUE TITLE
Never executed code

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#2989]
In the `editortoolkit_neume.cpp` there is a weird statement.
At this point `syllableFi` is always NULL, so the else block will never get executed.
https://github.com/rism-digital/verovio/blob/bb0c961574d0dbb5ce7253a82bec04fd32342e80/src/editortoolkit_neume.cpp#L1726-L1745

@JRegimbal could you please have a look there?

**Comment by JRegimbal** [comment]
Hi @rettinghaus, sorry for the delay! That does seem like a mistake that got through. My memory is fuzzy of this now, especially since I wasn't the only one working on this feature, but I think the else block contains leftover code of an attempted hybrid approach of using the `syllable`'s bounding box *and* the children's bounding boxes. This didn't ever seem to be a useful case in our testing and so it got split out into two cases, but that extra check of `syllableFi` and unused else statement got included.

It should be safe to replace this section with only lines 1727-1730.
