### ISSUE TITLE
getOption should return bool in Python toolkit

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3072]
**Describe the problem**
Many options carry boolean values, yet in the Python toolkit they are of type `str`. So e.g. `getOption("mmOutput")` returns the string `false` over the boolean `False`. 

Even worse `setOption("mmOutput", True)` doesn't work, not even `setOption("mmOutput", "1")`, you have to pass the string `"true"` to turn it on, which is rather unintuitive and not properly documented.

**To Reproduce**
```python
import verovio
tk = verovio.toolkit()
type(tk.getOption("mmOutput"))
```

returns `<class 'str'>`

**Expected behavior**
It should return real booleans and should accept booleans. 

**Verovio information**
 - latest develop
 - Python (macOS)

**Comment by lpugin** [comment]
We need to see what is reasonably possible to do with SWIG. But if it cannot be changed then you are right that it should be documented

**Comment by lpugin** [comment]
This is essentially a documentation issue. `GetOption` is documented to return a string
https://book.verovio.org/toolkit-reference/toolkit-methods.html#getoption

I agree that boolean are not very intuitive. Maybe you can add a section about options here:
https://book.verovio.org/installing-or-building-from-sources/python.html

I don't think having `getOption` returning different types is realistic

**Comment by lpugin** [comment]
Some more comments on this

1. I would be in favor of dropping `GetOption` because returning a string is not very useful and it will be really hard to make it simple across bindings. I guess this is why it was never made available in the JS toolkit. I do not think it is widely used.

2. I have been experimenting with way to avoid the need to transform Python dictionaries to string before passing them to Verovio for methods that take a JSON object or return one. This would be more inline with what we have with the JS toolkit where we can do:
```js
let scale = verovio.getOptions().scale
```
So in Python you would do
```python
scale = verovio.getOptions()['scale']
```
or even better
```python
scale = verovio.getOptions().get('scale')
```
This would work similarly the other way around for setting options
```python
verovio.setOptions({'mmOutput': True})
```
I've been reluctant to have additional binding code to do this. But I think there are ways to do it in a not too obtrusive way. It is still one more 'proxy' to maintain, though, but I think it would still be better.

3. If this all work, I would be in favor of dropping `SetOption` too and avoid additions like #3076. My experience is that it can be problematic in bindings when the distinction between methods is relying on type differences - typically between `bool` and `int`. So I would avoid it.

4. It will be difficult to have a deprecation phase when switching for strings to dictionaries, especially for values returned. So we should announce it in advance and make users aware that when we change it, the older function will not be available any more straight away.

5. This would make the Python toolkit more inline with the JS one, which is good. We still have other bindings (e.g., Java), which would still be string-based for JSON values.

**Comment by lpugin** [comment]
See #3077. 

(The `GetOptions` boolean parameter is a bit weird and not very intuitive. Maybe we should have `GetOptions` returning the current options, and another method `GetDefaultOptions` for the default ones, both without parameter)

**Comment by lpugin** [comment]
Adjusted with #3077
