### ISSUE TITLE
Remove build warnings

### ISSUE THREAD

**Issue by rettinghaus** [rism-digital/verovio#3078]
@craigsapp please fix the build warnings on `beamstartindex` and `beamendindex`.

**Comment by rettinghaus** [comment]
humlib.cpp:58948:46: implicit conversion loses integer precision
humlib.cpp:59289:35: implicit conversion loses integer precision

**Comment by ahankinson** [comment]
Losing integer precision is. :-D

**Comment by craigsapp** [comment]
There has been lots of discussions about signed and unsigned integers in the issues 😛 

They both take up the same space in in memory, and it is about interpretation of the bits.   For example a `char` is a one-byte signed int or unsigned int.  As an unsigned int it has the range from 0 to 255, but if interpreted as a signed int it is -128 to 127.   The common range between these two interpretations is 0 to 127.   So when numbers are within this range, there is no "loss of precision".   

When converting from a 8-byte int to a 4-byte int there will be a different sort of loss of precision since 4-bytes of the number are lost.

For a four byte number this shared range is 2^31 = 2147483648 (2 billion), so for 32-bit ints, the shared range for signed/unsigned is 0 to 2147483648.  And of course for 64-bit ints, this range will be larger (and equal to have of the total range of 64-bit ints.

When I use unsigned ints, I expect that the number will be significantly smaller than 2 billion, and in any case never go above 2 billion, such as counting the number of beams in a measure.   One reason why I use ints for small numbers is that if you subtract two unsigned ints from each other (such as to measure the difference between two numbers, or to go back one index in a vector) you have to be very careful to not generate a negative value, because there are no negative values in unsigned int world, and instead the result will be interpreted as a very large unsigned in.  For example, subtracting 1 from zero in an unsigned 4-byte int will generate the number 4294967297.

**Comment by craigsapp** [comment]
Who is supposed to merge the pull request? (https://github.com/rism-digital/verovio/pull/3082)

**Comment by rettinghaus** [comment]
I think you can go ahead.

**Comment by lpugin** [comment]
Some more for @craigsapp ;-)
```
./src/hum/humlib.cpp:3070:2 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.

./src/hum/humlib.cpp:58410:3 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.

./src/hum/humlib.cpp:72257:3 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.

./src/hum/humlib.cpp:72263:3 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.

./src/hum/humlib.cpp:72269:3 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.

./src/hum/humlib.cpp:72275:3 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.

./src/hum/humlib.cpp:110048:5 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.
```
