### ISSUE TITLE
Humdrum grace notes with no recip turn into MEI quarter-note grace notes with no stem

### ISSUE THREAD

**Issue by gregchapman-dev** [rism-digital/verovio#3083]
**Describe the problem**
Humdrum grace notes with no recip (e.g. "ee-q") are supposed to look like eighth notes.  And for a brief moment the duration defaults to '8', but then convertRhythm returns a duration of 0 (because there is no recip), and then convertNote decides that `dur == 0` means a quarter note with no stem.  I _think_ this is a recent regression, but I'm not sure.

**To Reproduce**
1. Load the data attached (Beethoven sonata06-2.krn)
2. Render any page (first example is in measure 6)
3. See that all grace notes are quarter notes with no stem (and this is what the MEI file says as well; not a rendering bug)

**Expected behavior**
All grace notes in this score should look like eighth notes.

**Input data**
Attached (sonata06-2.krn).

**Verovio information**
 - Version of Verovio: develop v3.13.0-dev-e2eebd6
 - Version of Verovio: humdrum-develop v3.13.0-dev-dd7573e (as used on verovio.humdrum.org)
 - Binding: Command line (develop) and JavaScript (humdrum-develop on verovio.humdrum.org)

**Environment information (as appropriate)**
 - OS: macOS
 - Browser: Safari

[sonata06-2.krn.zip](https://github.com/rism-digital/verovio/files/9823529/sonata06-2.krn.zip)

**Comment by gregchapman-dev** [comment]
Interestingly, the version of sonata06-2.krn posted on verovio.humdrum.org has been updated to add recip '8' to all the grace notes.

**Comment by craigsapp** [comment]
My current convention is to not show a stem when a grace note does not indicate a visual rhythm, such as `8q` for an eighth note grace note.  In other words, I now require a visual duration for the grace note, and will not show the stem if there is no visual duration:

<img width="998" alt="Screen Shot 2022-10-20 at 1 08 17 AM" src="https://user-images.githubusercontent.com/3487289/196894021-92a1268e-5bb8-44c4-83a2-59da78671ac9.png">

This is related to non-western repertories that use grace notes without stems.  In particular Indian classical music, where the westernized notation often includes stemless grace notes (at least in the repertory that I worked on related to this).

This behavior can be negotiated, but preferably if you want to see the grace note with a specific rhythm (and stem), then it is required to given the visual rhythm.  (The `q` indicates that the rhythm is visual rather than logical).

Many repertories in the VHV `scores` list now use this convention, but I have not yet finished editing Beethoven sonatas (you found one that was updated after you first downloaded it, so it is using the newer convention).

Since the stemless grace notes will typically only be found in non-western repertories, it is reasonable to otherwise assume an eighth-note grace note.  A smart thing to do would be to add and RDF record such as:

```
!!!RDF**kern: q = stemless
```

to indicate grace notes without visual rhythms should be stemless.   And/or an RDF record shown below to display grace notes that do not have a visual rhythm as eighth notes:

```
!!!RDF**kern: q = 8
```

Or currently not possible:

```
!!!RDF**kern: q = 8 stemless
```

which would mean that the unspecified grace notes are stemless, but they should have an implied visual duration of an eighth note.

<details>
<summary> Humdrum data for above example </summary>

```tsv
**kern
=1
qe
1f
=2
8qe
1f
=3
4qe
1f
=3
8qqe
1f
=4
4qqe
1f
=
*-
```
</details>

<details>
<summary> MEI conversion of example Humdrum data </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-10-20T01:13:34" version="3.13.0-dev-dd7573e-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m1uttd20">
    <score xml:id="s1kp6oop">
     <scoreDef xml:id="s1lqsqgm" midi.bpm="400.000000">
      <staffGrp xml:id="s12qtmks">
       <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
        <clef xml:id="cl28kkc" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-L1F1" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L3F1" dur="4" oct="4" pname="e" grace="unacc" stem.visible="false" accid.ges="n" />
         <note xml:id="note-L4F1" dur="1" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L5" n="2">
       <staff xml:id="staff-L5F1N1" n="1">
        <layer xml:id="layer-L5F1N1" n="1">
         <note xml:id="note-L6F1" dur="8" oct="4" pname="e" grace="unacc" accid.ges="n" />
         <note xml:id="note-L7F1" dur="1" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L8" n="3">
       <staff xml:id="staff-L8F1N1" n="1">
        <layer xml:id="layer-L8F1N1" n="1">
         <note xml:id="note-L9F1" dur="4" oct="4" pname="e" grace="unacc" accid.ges="n" />
         <note xml:id="note-L10F1" dur="1" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L11" n="3">
       <staff xml:id="staff-L11F1N1" n="1">
        <layer xml:id="layer-L11F1N1" n="1">
         <note xml:id="note-L12F1" dur="8" oct="4" pname="e" grace="acc" accid.ges="n" />
         <note xml:id="note-L13F1" dur="1" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
      <measure xml:id="measure-L14" n="4">
       <staff xml:id="staff-L14F1N1" n="1">
        <layer xml:id="layer-L14F1N1" n="1">
         <note xml:id="note-L15F1" dur="4" oct="4" pname="e" grace="acc" accid.ges="n" />
         <note xml:id="note-L16F1" dur="1" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

<details>

**Comment by gregchapman-dev** [comment]
Sounds good. Thanks.
