### ISSUE TITLE
Humdrum: `!!!filter: autobeam` leads to segmentation fault

### ISSUE THREAD

**Issue by malcolmsailor** [rism-digital/verovio#3142]
**Describe the problem**

The line `!!!filter: autobeam` in the attached humdrum file seems to lead to a segmentation fault. If the line is deleted, the segmentation fault goes away.

``` 
> verovio temp.krn
Should not get here in analyzeSpineStrands()
Should not get here in analyzeSpineStrands()
Should not get here in analyzeSpineStrands()
Should not get here in analyzeSpineStrands()
Segmentation fault: 11
```

The file was programmatically generated so it isn't very pretty. I deleted measures from the end until the segmentation fault went away in an attempt to zero in on the problem. I also tried deleting the initial measures but that seemed to make the segmentation fault go away.

There may very well be some syntax errors in the file but I haven't yet found them if there are. The file displays just fine at [https://verovio.humdrum.org/](https://verovio.humdrum.org/), with or without the autobeam filter.

**Verovio information**
 - Version of Verovio: Verovio 3.14.0-dev-1db2b94
 - Binding: command line

**Environment information (as appropriate)**
 - OS: MacOS

[temp.krn.zip](https://github.com/rism-digital/verovio/files/10099015/temp.krn.zip)

**Comment by craigsapp** [comment]
Here is the data from the zip file:

```tsv
**kern	**kern
*tb8	*tb8
*tb8	*
*	*^
*	*tb8	*tb8
=	=	=
*M4/4	*M4/4	*M4/4
8B	8dd	8f# 8dd
8B	8dd	8d
8A	8dd	8f# 8cc#
8A	8dd	8d
8G	8dd	8g 8b
8G	8dd	8d
8F#	8dd	8a
8F#	8dd	8d
=	=	=
8G	8dd	8b
8G	8dd	8d
8D	8dd	8f# 8a
8D	8cc#	8d
8GG	8cc#	8g 8b
8GG	8b	8d
8D	8a	8f# 8a
8D	8a	8d
*^	*	*
*	*^	*	*
=	=	=	=	=
4r	8BB 8D	4r	8g	8g
.	8BB 8D	.	8g	8d
2r	8D	8AA	8f#	8f#
.	8F#	8AA	8a	8f#
.	4A	2r	4f#	4d
8G	8AA	.	8f#	8c#
8G	8AA	.	8e	8c#
*	*	*	*	*^
=	=	=	=	=	=
8F#	8AA	8DD	2r	8d	8d
8F#	8BB	8DD	.	8d	8d
4r	8AA	8DD	.	4r	4r
.	8BB	8DD	.	.	.
4r	8AA	4r	8g	8g	4r
.	8BB	.	8g	8g	.
8A	8AA	8CC#	8g	8g	8e 8g
8A	8BB	8CC#	8a	8g	8e 8g
*	*	*	*	*v	*v
=	=	=	=	=
8A	8AA	8DD	8d 8f#	8f#
8A	8BB	8DD	8d 8f#	8f#
2.r	8AA	8DD	4r	4r
.	8BB	8DD	.	.
.	8AA	4r	4r	8a
.	8BB	.	.	8a
.	8AA	8EE	8g 8cc#	8cc#
.	8BB	8EE	8g 8cc#	8cc#
*	*v	*v	*	*^
*	*	*	*	*^
=	=	=	=	=	=
8AA	8FF#	8dd	8dd	8a	4r
8BB	8FF#	8dd	8dd	8a	.
8AA	8FF#	8ff#	8ff#	8a	2r
8D	8FF#	8ff#	8ff#	8a	.
8F#	4r	8ff#	8ff#	8a	.
8A	.	8ff#	8ff#	8a	.
8r	8G#	8ee	8ee	8e	8c#
8B	8G#	8dd	8dd	8e	8r
*	*	*	*	*v	*v
*	*	*	*v	*v
=	=	=	=
4A	4r	4cc#	4e 4cc#
8A	8D	8b	8f# 8b
8A	8C#	8cc#	8e 8cc#
4A	4BB	4dd	4f# 4dd
8E 8G#	4r	8dd	8d 8e
8E 8G#	.	8cc#	8d 8e
!!!filter: autobeam
```

The filter is working for me in Google Chrome on MacOS:

<img width="1751" alt="Screen Shot 2022-12-07 at 1 58 38 PM" src="https://user-images.githubusercontent.com/3487289/206305722-c0baaf30-942a-4920-bc53-1ed58cdb1cf8.png">

>  I deleted measures from the end until the segmentation fault went away in an attempt to zero in on the problem

By segmentation fault, does this mean you were using the command-line version of verovio?  I am getting the segmentation fault on the commad-line, so I suspect so.

The most likely problem is that the data is not terminated with `*-` tokens.   So technically the data is not in a valid states.  I allow converting to MEI when there is no data terminators in VHV so that the music can be displayed as you type it in.  Note that there is a warning when there is no termination line.

<img width="578" alt="Screen Shot 2022-12-07 at 2 07 27 PM" src="https://user-images.githubusercontent.com/3487289/206306999-f9cb76c0-8933-4e17-b80d-2914e3b401be.png">

Adding these terminators is likely to fix the problem.   I tried that with the test data on the command-line, and that fixed the problem.

Since Humdrum filters are not a direct part of verovio and instead come from the humlib repository, it is better to report this problem to

https://github.com/craigsapp/humlib/issues

I did that with issue https://github.com/craigsapp/humlib/issues/54

(or it can be reported on the VHV repository issues, but ultimately it is a problem to handle more gracefully in humlib).
