### ISSUE TITLE
Expose skipLayoutOnLoad() in toolkit

### ISSUE THREAD

**Issue by wergo** [rism-digital/verovio#3218]
With PR #2932, @DavidBauer1984 introduced a nice flag to skip time-intensive layout processing when merely requesting MIDI or timemap through the commend line. 

It seems that this feature cannot be accessed from the toolkit. Am I missing something here? 

It would be great to expose it to the toolkit too.

**Comment by rettinghaus** [comment]
It's available in the Python toolkit, but nowhere documented. Perhaps we should also move it out from the _nodoc_ group?

**Comment by DavidBauer1984** [comment]
When using Verovio as command-line program we don't need an extra option. We already have full information and know when to skip the layout (i.e. depending on the output format).

When using it as toolkit, we need some extra information. When calling `Load` after construction of the toolkit, the toolkit doesn't know what the user intends to do with it, i.e. if layout is required for later commands such as rendering. So in my view there are two alternatives:

1. We create an option. Then it would be neat, if the value was calculated from the output format on the command line program while it should be switched off per default on the toolkit. This feels a bit awkward compared to other options.

2. Make it available via toolkit API.

I refrained from making the functionality available in the toolkit, since skipping the layout can lead to problems, if not used properly. It should be activated only, if the toolkit is not used for any rendering purposes. If the user loads the MEI without layout and then calls `Render`, this probably leads to a crash. We can leave this hazard to the user or must improve error handling.

**Comment by wergo** [comment]
> It's available in the Python toolkit, but nowhere documented. Perhaps we should also move it out from the _nodoc_ group?

@rettinghaus Where do I see that this method exposed for the Python toolkit? I cannot find it in `/bindings/python/verovio.i`.

**Comment by wergo** [comment]
@DavidBauer1984 Thanks a lot for your reply. 

Independently whether it is an option or exposed as part of the API, if data is loaded to the toolkit with the rendering-skipped option and renderToSvg() methods are called afterwards, the toolkit should go and rerender the layout then. What do you think?

**Comment by rettinghaus** [comment]
@wergo swig provides all public methods in the toolkit. In `verovio.i` we simply redefine a set of methods to be more Pythonic.

**Comment by wergo** [comment]
@rettinghaus Ah, I see. Thanks a lot.

**Comment by DavidBauer1984** [comment]
> Independently whether it is an option or exposed as part of the API, if data is loaded to the toolkit with the rendering-skipped option and the `renderToSvg()` method is called afterwards, the toolkit should go and re-render the layout then.

Yes, ideally it should be like this from a user perspective. It would probably require some extra work on the implementation side, but it's definitely doable.

**Comment by wergo** [comment]
@DavidBauer1984 What about not doing rendering when `loadData()` is called, but initiating it, when methods are called that are requiring a rendering, such as `renderToSvg()`?

**Comment by lpugin** [comment]
> What about not doing rendering when `loadData()` is called, but initiating it, when methods are called that are requiring a rendering, such as renderToSvg()?

That should be only if the option `skipLayoutOnLoad`is explicitly set to `true` (default would be `false`). The behaviour would be similar to `breaks none`. You would have to call `redoLayout` to be back to a result corresponding to the `breaks` option (e.g., `auto`)

**Comment by wergo** [comment]
> The behaviour would be similar to `breaks none`. 

So this would solve my request: just set `breaks` to `none` if you want to get a Midi file and Verovio does not render the layout?

**Comment by lpugin** [comment]
@wergo I think this is now only a documentation issue, which we should add to the `renderToTimemap` method?

**Comment by rettinghaus** [comment]
The main problem is still that this method is not available in the JavaScript toolkit. We have to add it to emscripten.

**Comment by rettinghaus** [comment]
@wergo Tried to add it in #3228, please have a look.

**Comment by lpugin** [comment]
See See https://github.com/rism-digital/verovio-reference-book/commit/103bd4fdafa6217d4343863db3458035cc92c895

We should remove `Toolkit::SkipLayoutOnLoad` and `Toolkit::m_skipLayoutOnLoad` because the only place where it is used is in `main.cpp` and replaced it with `toolkit.SetOptions("{'breaks': 'none'}");` does exactly the same. Then the issue can be closed.

**Comment by wergo** [comment]
It is not directly intuitive from a user perspective, but it does the job. Thanks a lot!
