### ISSUE TITLE
--incipit enhancement

### ISSUE THREAD

**Issue by craigsapp** [rism-digital/verovio#3239]
The `--incipit` option will render `<incipit>` data in the MEI header.  It might be nice to add an enhancement: if there are no incipit elements in the file, then render the first system of the score.   Does this option render multiple `<incipits>` and if so, then do something similar with multiple `<mdiv>`.

Automatic incipits can currently be done with the options `--set-page-height 1` and `--adjust-page-height` to generate a page containing only the first system of music.   So this feature is not critical; however, it would be useful to allow it since it is not otherwise obvious how to do this to the general verovio user.

**Comment by lpugin** [comment]
I am not really convinced that having the `--incipit` option doing different things depending on the content is really a good idea. It would be confusing. 

However, as you said, since we can already do it by adjusting options, I simply added some documentation. You are right this was missing: https://book.verovio.org/advanced-topics/layout-options.html#generating-single-system-incipits
