### ISSUE TITLE
mixed beam rendering & pitch interaction

### ISSUE THREAD

**Issue by frakel** [rism-digital/verovio#3250]
Verovio currently  does not always respect the `@stem.dir:up|down` directive in `beam@place:mixed`. This inconsistent behaviour depends apparently on the pitch of the encoded music:
![image](https://user-images.githubusercontent.com/5627140/216656796-10920e2c-4f36-4105-a212-805a85fc45f4.png)

<details><summary>Click here for the code</summary><p>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.1/mei-CMN.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.1/mei-CMN.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei meiversion="4.0.0" xmlns="http://www.music-encoding.org/ns/mei">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title label="NMA digital" type="unit">an example</title>
        <contributor>dime</contributor>
      </titleStmt>
      <pubStmt/>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef meter.count="4" meter.sym="common" meter.unit="4">
            <staffGrp>
              <staffDef clef.line="2" clef.shape="G" lines="5" n="1" xml:id="sd1"/>
            </staffGrp>
          </scoreDef>
          <section>
            <measure xml:id="bbK80-3-2-13">
              <staff n="1" xml:id="bbstaff_9240">
                <layer n="1" xml:id="bblayer_9246">
                  <beam place="mixed" xml:id="bbbeam_9252">
                    <note dur="8" oct="3" pname="e" stem.dir="up" xml:id="bbnote_9258"/>
                    <note dur="8" oct="5" pname="e" stem.dir="down" xml:id="bbnote_9264"/>
                    <note dur="8" oct="5" pname="d" stem.dir="down" xml:id="bbnote_9270"/>
                    <note dur="8" oct="5" pname="c" stem.dir="down" xml:id="bbnote_9276"/>
                    <note dur="8" oct="4" pname="b" stem.dir="down" xml:id="bbnote_9282"/>
                    <note dur="8" oct="4" pname="a" stem.dir="down" xml:id="bbnote_9288"/>
                  </beam>
                </layer>
              </staff>
            </measure>
            <measure xml:id="bK80-3-2-13">
              <staff n="1" xml:id="bstaff_9240">
                <layer n="1" xml:id="blayer_9246">
                  <beam place="mixed" xml:id="bbeam_9252">
                    <note dur="8" oct="3" pname="f" stem.dir="up" xml:id="bnote_9258"/>
                    <note dur="8" oct="5" pname="f" stem.dir="down" xml:id="bnote_9264"/>
                    <note dur="8" oct="5" pname="e" stem.dir="down" xml:id="bnote_9270"/>
                    <note dur="8" oct="5" pname="d" stem.dir="down" xml:id="bnote_9276"/>
                    <note dur="8" oct="5" pname="c" stem.dir="down" xml:id="bnote_9282"/>
                    <note dur="8" oct="4" pname="b" stem.dir="down" xml:id="bnote_9288"/>
                  </beam>
                </layer>
              </staff>
            </measure>
            <measure xml:id="K80-3-2-13">
              <staff n="1" xml:id="staff_9240">
                <layer n="1" xml:id="layer_9246">
                  <beam place="mixed" xml:id="beam_9252">
                    <note dur="8" oct="3" pname="g" stem.dir="up" xml:id="note_9258"/>
                    <note dur="8" oct="5" pname="g" stem.dir="down" xml:id="note_9264"/>
                    <note dur="8" oct="5" pname="f" stem.dir="down" xml:id="note_9270"/>
                    <note dur="8" oct="5" pname="e" stem.dir="down" xml:id="note_9276"/>
                    <note dur="8" oct="5" pname="d" stem.dir="down" xml:id="note_9282"/>
                    <note dur="8" oct="5" pname="c" stem.dir="down" xml:id="note_9288"/>
                  </beam>
                </layer>
              </staff>
            </measure>
            <measure xml:id="a-K80-3-2-13">
              <staff n="1" xml:id="a-staff_9240">
                <layer n="1" xml:id="a-layer_9246">
                  <beam place="mixed" xml:id="a-beam_9252">
                    <note dur="8" oct="3" pname="a" stem.dir="up" xml:id="a-note_9258"/>
                    <note dur="8" oct="5" pname="a" stem.dir="down" xml:id="a-note_9264"/>
                    <note dur="8" oct="5" pname="g" stem.dir="down" xml:id="a-note_9270"/>
                    <note dur="8" oct="5" pname="f" stem.dir="down" xml:id="a-note_9276"/>
                    <note dur="8" oct="5" pname="e" stem.dir="down" xml:id="a-note_9282"/>
                    <note dur="8" oct="5" pname="d" stem.dir="down" xml:id="a-note_9288"/>
                  </beam>
                </layer>
              </staff>
            </measure>
            <measure xml:id="aa-K80-3-2-13">
              <staff n="1" xml:id="aa-staff_9240">
                <layer n="1" xml:id="aa-layer_9246">
                  <beam place="mixed" xml:id="aa-beam_9252">
                    <note dur="8" oct="3" pname="b" stem.dir="up" xml:id="aa-note_9258"/>
                    <note dur="8" oct="5" pname="b" stem.dir="down" xml:id="aa-note_9264"/>
                    <note dur="8" oct="5" pname="a" stem.dir="down" xml:id="aa-note_9270"/>
                    <note dur="8" oct="5" pname="g" stem.dir="down" xml:id="aa-note_9276"/>
                    <note dur="8" oct="5" pname="f" stem.dir="down" xml:id="aa-note_9282"/>
                    <note dur="8" oct="5" pname="e" stem.dir="down" xml:id="aa-note_9288"/>
                  </beam>
                </layer>
              </staff>
            </measure>
            <measure xml:id="aaa-K80-3-2-13">
              <staff n="1" xml:id="aaa-staff_9240">
                <layer n="1" xml:id="aaa-layer_9246">
                  <beam place="mixed" xml:id="aaa-beam_9252">
                    <note dur="8" oct="4" pname="c" stem.dir="up" xml:id="aaa-note_9258"/>
                    <note dur="8" oct="6" pname="c" stem.dir="down" xml:id="aaa-note_9264"/>
                    <note dur="8" oct="5" pname="b" stem.dir="down" xml:id="aaa-note_9270"/>
                    <note dur="8" oct="5" pname="a" stem.dir="down" xml:id="aaa-note_9276"/>
                    <note dur="8" oct="5" pname="g" stem.dir="down" xml:id="aaa-note_9282"/>
                    <note dur="8" oct="5" pname="f" stem.dir="down" xml:id="aaa-note_9288"/>
                  </beam>
                </layer>
              </staff>
            </measure>
            <measure xml:id="aaaa-K80-3-2-13">
              <staff n="1" xml:id="aaaa-staff_9240">
                <layer n="1" xml:id="aaaa-layer_9246">
                  <beam place="mixed" xml:id="aaaa-beam_9252">
                    <note dur="8" oct="4" pname="d" stem.dir="up" xml:id="aaaa-note_9258"/>
                    <note dur="8" oct="6" pname="d" stem.dir="down" xml:id="aaaa-note_9264"/>
                    <note dur="8" oct="6" pname="c" stem.dir="down" xml:id="aaaa-note_9270"/>
                    <note dur="8" oct="5" pname="b" stem.dir="down" xml:id="aaaa-note_9276"/>
                    <note dur="8" oct="5" pname="a" stem.dir="down" xml:id="aaaa-note_9282"/>
                    <note dur="8" oct="5" pname="g" stem.dir="down" xml:id="aaaa-note_9288"/>
                  </beam>
                </layer>
              </staff>
            </measure>
            <measure xml:id="aaaaa-K80-3-2-13">
              <staff n="1" xml:id="aaaaa-staff_9240">
                <layer n="1" xml:id="aaaaa-layer_9246">
                  <beam place="mixed" xml:id="aaaaa-beam_9252">
                    <note dur="8" oct="4" pname="e" stem.dir="up" xml:id="aaaaa-note_9258"/>
                    <note dur="8" oct="6" pname="e" stem.dir="down" xml:id="aaaaa-note_9264"/>
                    <note dur="8" oct="6" pname="d" stem.dir="down" xml:id="aaaaa-note_9270"/>
                    <note dur="8" oct="6" pname="c" stem.dir="down" xml:id="aaaaa-note_9276"/>
                    <note dur="8" oct="5" pname="b" stem.dir="down" xml:id="aaaaa-note_9282"/>
                    <note dur="8" oct="5" pname="a" stem.dir="down" xml:id="aaaaa-note_9288"/>
                  </beam>
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>

```
</details>

Thanks for fixing this!

**Comment by rettinghaus** [comment]
There are several rules conflicting. In the upper example the beam would need to go above the ledger lines forcing it to go into the wrong direction. In the lower line all beams are going upwards.

Have you tried `beamMixedStemMin` and `beamMixedPreserve` options?

**Comment by frakel** [comment]
Thank you @rettinghaus ! With `beamMixedPreserve` I get the desired output for the example above:
![image](https://user-images.githubusercontent.com/5627140/217601278-0f85b6b3-c8a6-41bd-9db1-245fd268265c.png)

**Comment by craigsapp** [comment]
That is an interesting case.  Ideally the rendering of the beams would be closer to this:

<img width="1536" alt="Screenshot 2023-02-08 at 9 40 35 AM" src="https://user-images.githubusercontent.com/3487289/217609279-2732990f-9111-43d6-a219-9e95c2b9c3ff.png">

<details>
<summary> Click to view SCORE data for above example </summary>

```tsv
8  1   0.000  0.0  0.7 200.00
3  1   1.500
18 1   6.749  0.0 99.0   1.00
1  1  11.999 -4.0 10.0   0.00  0.5  3.00
6  1  11.999 -1.0 -6.5  28.98 11.0  0.00 0 0 0 0 0  0 20
1  1  16.199 10.0 20.0   0.00  0.5 -1.19
1  1  19.394  9.0 20.0   0.00  0.5 -1.02
1  1  22.590  8.0 20.0   0.00  0.5 -0.84
1  1  25.785  7.0 20.0   0.00  0.5 -0.67
1  1  28.980  6.0 20.0   0.00  0.5 -0.50
14 1  32.830  1.0
1  1  34.645 -3.0 10.0   0.00  0.5  2.00
6  1  34.645 -1.0 -6.0  51.63 11.0  0.00 0 0 0 0 0  0 20
1  1  38.845 11.0 20.0   0.00  0.5 -0.26
1  1  42.041 10.0 20.0   0.00  0.5 -0.20
1  1  45.236  9.0 20.0   0.00  0.5 -0.13
1  1  48.431  8.0 20.0   0.00  0.5 -0.07
1  1  51.627  7.0 20.0   0.00  0.5
14 1  55.477  1.0
1  1  57.291 -2.0 10.0   0.00  0.5  2.00
6  1  57.291  0.0 -4.0  74.27 11.0  0.00 0 0 0 0 0  0 20
1  1  61.491 12.0 20.0   0.00  0.5 -0.41
1  1  64.687 11.0 20.0   0.00  0.5 -0.56
1  1  67.882 10.0 20.0   0.00  0.5 -0.70
1  1  71.077  9.0 20.0   0.00  0.5 -0.85
1  1  74.273  8.0 20.0   0.00  0.5 -1.00
14 1  78.123  1.0
1  1  79.938 -1.0 10.0   0.00  0.5  1.00
6  1  79.938  0.0 -4.0  96.92 11.0  0.00 0 0 0 0 0  0 20
1  1  84.138 13.0 20.0   0.00  0.5  0.59
1  1  87.333 12.0 20.0   0.00  0.5  0.44
1  1  90.528 11.0 20.0   0.00  0.5  0.30
1  1  93.724 10.0 20.0   0.00  0.5  0.15
1  1  96.919  9.0 20.0   0.00  0.5
14 1 100.769  1.0
1  1 102.584  0.0 10.0   0.00  0.5  0.50
6  1 102.584 13.5  9.5 120.43 21.0  0.00 0 0 0 0 0 10
1  1 106.784 14.0 20.0   0.00  0.5  1.06
1  1 110.844 13.0 20.0   0.00  0.5  1.08
1  1 114.039 12.0 20.0   0.00  0.5  0.89
1  1 117.234 11.0 20.0   0.00  0.5  0.69
1  1 120.430 10.0 20.0   0.00  0.5  0.50
14 1 124.280  1.0
1  1 126.095  1.0 10.0   0.00  0.5
6  1 126.095 14.0 11.0 144.81 21.0  0.00 0 0 0 0 0 10
1  1 130.295 15.0 20.0   0.00  0.5  1.40
1  1 134.355 14.0 20.0   0.00  0.5  1.13
1  1 138.415 13.0 20.0   0.00  0.5  0.85
1  1 141.610 12.0 20.0   0.00  0.5  0.43
1  1 144.805 11.0 20.0   0.00  0.5
14 1 148.655  1.0
1  1 150.470  2.0 10.0   0.00  0.5  0.50
6  1 150.470 15.5 11.5 170.05 21.0  0.00 0 0 0 0 0 10
1  1 154.670 16.0 20.0   0.00  0.5  1.00
1  1 158.730 15.0 20.0   0.00  0.5  0.93
1  1 162.790 14.0 20.0   0.00  0.5  0.85
1  1 166.850 13.0 20.0   0.00  0.5  0.77
1  1 170.045 12.0 20.0   0.00  0.5  0.50
14 1 173.895  1.0
1  1 175.710  3.0 10.0   0.00  0.5 -0.50
6  1 175.710 15.5 12.0 196.15 21.0  0.00 0 0 0 0 0 10
1  1 179.910 17.0 20.0   0.00  0.5  1.92
1  1 183.970 16.0 20.0   0.00  0.5  1.69
1  1 188.030 15.0 20.0   0.00  0.5  1.46
1  1 192.090 14.0 20.0   0.00  0.5  1.23
1  1 196.150 13.0 20.0   0.00  0.5  1.00
14 1 200.000  1.0
```

</details>


Verovio is only considering the endpoint notes rather than looking at the contour of the last five notes which are more important.   This is resulting in the stem length of the first note being very short, and then resulting in it being rejected as a mixed-stem beam unless `beamMixedPreserve` is given.

**Comment by frakel** [comment]
yes, in Verovio the slope of the beams goes into the wrong direction, would be nice to get this right. 
But however, at the moment it meets my modest expectations 😉

**Comment by craigsapp** [comment]
It is difficult to fully optimize the placement of the beam in mixed stem cases, so to solve the general case of mix-beam rendering, `note@stem.dir` would be needed on the first and last note of the beamed note group.

**Comment by cividini** [comment]
The rendering of the beam direction considering only the end point notes, as actually rendered in Verovio (and implied by @rettinghaus [in his comment](https://github.com/rism-digital/verovio/issues/3250#issuecomment-1416118318)), is correct, s. Behind Bars, p. 22:

![grafik](https://user-images.githubusercontent.com/45197272/217741076-cdc7706c-21f8-4b82-a770-ba0cdc69fbb3.png)

The problem here is that it is impossible to apply this (quite unintuitive) rule without a collision of the beam with the ledger lines in the first four measures of the [example above](https://github.com/rism-digital/verovio/issues/3250#issuecomment-1422956720). When there is no collision with ledger lines, the rendering of the mixed beam in Verovio is indeed implemented, as in the last four measures of the [example above](https://github.com/rism-digital/verovio/issues/3250#issuecomment-1422956720).

So the editor/encoder has here (first four measures of the [example above](https://github.com/rism-digital/verovio/issues/3250#issuecomment-1422956720)) to choose between Scylla and Charybdis: either force the beam to be mixed through `beamMixedPreserve` or let Verovio render no mixed beam in order to avoid the collision with the ledger lines. As editor I prefer to avoid the collision with the ledger lines and sacrifice the mixed beamed as Verovio does.

By the way: Behind Bars does not consider this collision possibility in its examples. May be Elaine Gould would have suggested for this case a rule exception and a rendering with an horizontal beam or with a beam in the opposite direction as proposed by @craigsapp in his [example above](https://github.com/rism-digital/verovio/issues/3250#issuecomment-1423008292).

**Comment by cividini** [comment]
An example of an exception from the rule for the rendering of the beam is given in NMA, KV 80/3, Trio, m. 13: 
![NMA_Knickbalken](https://user-images.githubusercontent.com/45197272/217750907-ce9b863b-7af3-48ea-be0c-a99ff1a07135.png)

Here the beam goes exceptionally in the opposite direction (against the general rule in Behind Bars) in order to avoid the collision with the ledger lines, as suggested by @craigsapp in [his comment](https://github.com/rism-digital/verovio/issues/3250#issuecomment-1423008292). So only when there is a collision with the ledger lines we have to force the beam in the opposite direction (against the general rule) with `note@stem.dir`.

**Comment by craigsapp** [comment]
> The rendering of the beam direction considering only the end point notes, as actually rendered in Verovio (and implied by `@rettinghaus` https://github.com/rism-digital/verovio/issues/3250#issuecomment-1416118318), is correct, s. Behind Bars, p. 22:

Yes, when all of the stems are on the same side of the noteheads, this rendering is correct in verovio:

<img width="924" alt="Screenshot 2023-02-08 at 11 53 06 PM" src="https://user-images.githubusercontent.com/3487289/217750602-40dbcb5c-7606-4ed2-b9ec-9c3da78cb3e2.png">

The problem is that with the mixed directions of stems with the beam in the middle, this is very ugly:

<img width="927" alt="Screenshot 2023-02-08 at 11 54 13 PM" src="https://user-images.githubusercontent.com/3487289/217750776-21d6d72e-99c0-4301-a327-82d27652d025.png">

I have not seen the original manuscript/print of this music, but I can easily infer that the correct rendering should be:

<img width="905" alt="Screenshot 2023-02-08 at 11 55 00 PM" src="https://user-images.githubusercontent.com/3487289/217750939-e78803e3-4cf5-48b4-ac75-a0b1bd39085d.png">

When the mixed beam is rendered like this, there is no problems with collisions with ledger lines.

Future refinements will be needed for mix-stem beams, but probably along with an analysis of what algorithms might be used in manually typeset music.

**Comment by craigsapp** [comment]
> Here the beam goes exceptionally in the opposite direction (against the general rule in Behind Bars) 

The rules in Behind Bars are only for when stems are all in the same direction.  That placement of the beam is the standard position when the stem directions are mixed up and down, and the Behind Bars rules do not apply to this mix-stem case:

<img width="211" alt="Screenshot 2023-02-09 at 12 04 59 AM" src="https://user-images.githubusercontent.com/3487289/217752926-055ff522-964e-4c03-b51a-1ad1738ee741.png">

**Comment by cividini** [comment]
@craigsapp: In Behind Bars, the same general rule applies also for beams with stems in opposite direction, see p. 26 ("slope the beam in the direction of the outside interval"):

![grafik](https://user-images.githubusercontent.com/45197272/217755742-b2c4ef78-bf71-4bf2-a3b4-53a30a26b07f.png)

But I do agree that there are cases in which this general rule does not apply, for example when there is a collision with the ledger lines as in our case as in the first four measures in your [example above](https://github.com/rism-digital/verovio/issues/3250#issuecomment-1423008292). I am not sure if we need an exception from the general rule for the last four measures. Behind Bars doesn't give a hint on that (and is not the bible). So I think that it will be difficult to find an algorithm for all cases in Verovio. The best at the moment to decide from case to case with using `note@stem.dir` as you suggested.

**Comment by craigsapp** [comment]
> The best at the moment to decide from case to case with using note@stem.dir as you suggested.

Yes that would be the easiest solution, and in general the mixed-stem beam positions should not change when transposing the music, unlike regular beams.

A simple fix to make mixed-stems beaming look better in general would be to first try a beam between the ending notes of the mixed beam with standard octave-length stems (or extended to the center line for notes with ledger lines): if there is no collision of this beam with notes inside of the beam (and internal notes all have acceptable-length stems), then use this simple placement; otherwise, fall back to the current algorithm.

**Comment by cividini** [comment]
Just to make the question more complicated: Behind Bars applies the general outside-notes-rule for the beam direction in mixed beams also between two staves, see p. 315: "otherwise, reflect the interval of the outside notes (b)", but at the same time allows an exception when "the direction of the ouside pitches contradicts the direction of the majoritiy of notes (c)" as in our example:

![grafik](https://user-images.githubusercontent.com/45197272/217762808-6743a8ad-e550-4b6f-99c4-db1abf842dac.png)

For this case Behind Bars suggests horizontal beams, if there is the possibility to place them between the staves (which is not possible in our case).
