### ISSUE TITLE
Android: WebAssembly.instantiate(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by cambiata** [rism-digital/verovio#3277]
**Describe the problem**
On some older Android devices, and sometimes in the Android emulator, Verovio doesn't instatiate correctly but instead gives the following error output:

```
failed to asynchronously prepare wasm: RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
(anonymous) @ cbcb57f3.9d95b790b68c7e41.js:1
Promise.then (async)
C @ cbcb57f3.9d95b790b68c7e41.js:1
...

Aborted(RangeError: WebAssembly.instantiate(): Out of memory: wasm memory)
...

Uncaught (in promise) RuntimeError: Aborted(RangeError: WebAssembly.instantiate(): Out of memory: wasm memory). Build with -s ASSERTIONS=1 for more info.
    at v (https://dev-webapp-wav-player2.azurewebsites.net/_next/static/chunks/cbcb57f3.9d95b790b68c7e41.js:1:3054079)
    at https://dev-webapp-wav-player2.azurewebsites.net/_next/static/chunks/cbcb57f3.9d95b790b68c7e41.js:1:6939581
...
```
I'm using the "Basic usage with NPM" instantiation method (`verovio.module.onRuntimeInitialized = function () { . . . }`) in a React framework application. (No luck trying to use "Usage with ESM" method with React unfortunately.)

At the least, I would like to be able to catch the error and display a decent error message to the user - but I haven't had any luck in catching the error at all.
Does anyone have an idea how to deal with this?

Best! / Jonas

**Comment by WolfgangDrescher** [comment]
Do you use multiple instances of Verovio on the same page? I recently ran into a memory limit when I had a list with multiple score examples and had to change the setup slightly. Have a look at this discussion: https://github.com/rism-digital/verovio/discussions/3162

Also check out the repository I created to test all use cases when I integrated ESM support for Verovio. There is a react example as well: https://github.com/WolfgangDrescher/verovio-npm-examples/tree/master/react-app (I'm not a React dev). Note that since v3.14.0 the Module itself is actually a ES6 module because there were some changes in Emscripten. Before just the toolkit was ESM ready and the Module was actually CJS that can be imported by ESM.

https://github.com/WolfgangDrescher/verovio-npm-examples/blob/master/react-app/src/App.js#LL2-L3C42

These two lines should be the following for the final version that ended up in Verovio: 

```js
import Module from 'verovio/wasm';
import { VerovioToolkit } from 'verovio/esm';
```

And I would recommend to rename `Module` with `createVerovioModule` because it follows the factory pattern.

Also note that I would recommend to use verovio as a web worker. Take this https://github.com/WolfgangDrescher/vue-verovio-canvas as inspiration. Be careful with Firefox. As I recently discovered Firefox does not support yet web workers with type `module`. So you should probably use `importScript()` inside the worker.

**Comment by lpugin** [comment]
Thanks @WolfgangDrescher. Closing for now since there is not really enough information to say more about it.
