### ISSUE TITLE
Fit score on two pages?

### ISSUE THREAD

**Issue by sonovice** [rism-digital/verovio#3310]
I have seen the feature "Scale to fit on two pages" on this website utilizing Verovio: https://my.hymnary.org/song/1758/i-know-the-lords-laid-his-hands-on-me?instrument=full&nPages=2

Now I am curious how this can be achieved with the available Verovio Options since I cannot wrap my head around it. Any hints would be highly appreciated.

EDIT: Apart from searching for the right `scale` via `GetPageCount()` and brute bisection. :smile:

**Comment by lpugin** [comment]
As far as I can think there is currently no way to achieve this. It seems a pretty specific use case, though. Maybe you should contact the my.hymnary.org people to ask how they do it?

It seems that the overall goal of what you are looking for is a way to target a certain number of pages, which does not look like something straight forward to implement.

**Comment by sonovice** [comment]
Thanks for the answer, @lpugin ! That's what I thought as well. I am not particularly interested in replicating that feature, it just made me really curious how it could be achieved.

**Comment by craigsapp** [comment]
For the Josquin Research Project, I adjust horizontal spacing parameters to try to get a full page of music on the last page, or otherwise have reasonable automatic line breaks and page turns.

Here is an example where the music fills four full pages:
https://josquin.stanford.edu/cgi-bin/jrp?a=notationEditText&f=Jos2102

<img width="557" alt="Screenshot 2023-03-07 at 10 21 13 AM" src="https://user-images.githubusercontent.com/3487289/223514456-720c4deb-378b-422b-8ec5-0dd9870db5a6.png">

This is controlled by embedded rendering [options](https://wiki.ccarh.org/wiki/Muse2ps#Options) in the file that are read when rendering to notation with [muse2ps](https://wiki.ccarh.org/wiki/Muse2ps):

https://github.com/josquin-research-project/Jos/blob/main/Jos2102-Ave_verum_corpus.krn#L646

```
!!muse2ps: C^@{COM}^i2I150v90,90,120c135z18l2700t130
```

In this case `c135` (compression factor 135%) is the primary parameter that I adjust to get the music on the last page to fill the page.

For verovio, this would mostly involve adjusting `spacingLinear` and `spacingNonLinear`.   For Hymnary.org, notice that notation scaling is also used to create a one-page version of the score.  The one-page version on the above cited page is not greatly adjusted to fit the page, because verovio is justifying the  last system (so it is sparsely populated compared to other systems in the music -- so the spacing of the music would ideally be increased a bit to make the last system more full).

It would be possible to automatically search for possible page counts, but only practical on the command-line: you can adjust parameters to verovio, and then observe the number of pages that are produced.  If there are too many, then you make the music more compact or smaller, and if there are too few pages, then you increase the musical spacing and/or size of the music.   For example, for fitting onto two pages, keep increasing the music spacing until the number of pages becomes 3 pages.   This means that one step less will generate a full two-page PDF.

Doing this within verovio would be problematic: for dynamic notation this process has an unknown duration to calculate the best layout such as filling the last page (or system).

-------------------------------------

Issue https://github.com/rism-digital/verovio/issues/3280 is related to this sort of thing.  Embedding rendering options in the MEI score would allow tweaking the spacing to get optimal layout, such as to fill out the last page of the score.   Note in particular that the concepts of "option sets" would be useful in this particular case.   Here are example possible option sets that could be embedded:

| option | meaning |
| `--embedded-option-set pdf` | Apply options to create PDF file of score |
| `--embedded-option-set pdf-a4` | Apply options to create PDF file of score in A4 format |
| `--embedded-option-set pdf-two-page` | Apply options to create a two page PDF file |

Different scaling and spacing settings could be given for each target media/layout.

Note that such a system is implemented for storing verovio parameters in Humdrum scores:

https://doc.verovio.humdrum.org/options

Example:

```
!!!verovio: spacingStaff 0
!!!verovio-compact: spacingStaff 0
!!!verovio-spacious: spacingStaff 20
!!!verovio-parameter-group: spacious
```

The last line is equivalent to `--embedded-options-set spacious`.   This will case all `verovio-spacious` lines to be read for options as well as the plain `verovio` entries which are applied to all groups.

--------------------------

You can also force linebreaks to add more refinement to the layout.   This is a manual process, of course.  In Humdrum I assign "groups" to line/page breaks, such as:

```
!!LO:LB:g=original
```

which means that this is a line break in the reference printed edition used to create the digital edition.   This system can be used for printing to PDF in various formats such as letter/A4/landscape (although I don't do that yet).   But I do enable line breaks when I want the original layout for the digital edition (in order to proofread the digital edition):

https://verovio.humdrum.org/?file=beethoven/sonatas/sonata01-1.krn

<img width="1788" alt="Screenshot 2023-03-07 at 11 12 01 AM" src="https://user-images.githubusercontent.com/3487289/223527340-8c6db658-69c3-4be4-8d44-7fbca2ca7279.png">

There is a button on the top right of the VHV page:

<img width="54" alt="Screenshot 2023-03-07 at 11 16 03 AM" src="https://user-images.githubusercontent.com/3487289/223527532-dd69aaff-e48e-47bf-9bf1-5c3d802ff9e3.png">

That toggles line breaks in the verovio rendering.   Here is the layout using automatic linebreaks:


<img width="1066" alt="Screenshot 2023-03-07 at 11 17 58 AM" src="https://user-images.githubusercontent.com/3487289/223527783-3a43ea83-7a90-4389-95b8-422ed66c75fe.png">

And if I did not like it to be as compact, I can increase the `spacingLinear` parameter with `option-w` in VHV to approximate the original spacing (I pressed `option-w` three times to get at least the first three systems matching the printed edition automatically):

<img width="1074" alt="Screenshot 2023-03-07 at 11 19 09 AM" src="https://user-images.githubusercontent.com/3487289/223528125-cfc00f70-62de-41ad-afcc-5a3c8d21a727.png">

You could do something similar in MEI to encode different system breaks for different target layouts, such as with `<app>`: https://music-encoding.org/guidelines/v4/content/scholarlyediting.html

And then use `--app-x-path-query` or `--choice-x-path-query` or similar to select the system breaks for the manually optimized layout that you encoded in the score for a particular output format.

**Comment by samuelbradshaw** [comment]
@earboxer

**Comment by sonovice** [comment]
Thanks, @samuelbradshaw ! I've just contacted him via XMPP.

**Comment by bryantgeorge** [comment]
I couldn't find a C rewrite, but we recently rewrote this code in C++. Here's the relevant code:

```cpp
double FlexScore::computeSpacingLinear(int unit)
{
    return std::max((0.3 * unit) / 10, 0.25);
}

int FlexScore::fitToNPages()
{
    const int MIN_UNIT = 6;
    const int MAX_UNIT = 20;
    std::vector<int> units;
    // '+ 1' since upper_bound() points to the entry after the target, so
    // no need to test the minimum value.
    for (int i = MIN_UNIT + 1; i <= MAX_UNIT; ++i) {
        units.push_back(i);
    }
    auto target = std::upper_bound(
        units.begin(),
        units.end(),
        nPages,
        [this](int pageTarget, int unit) {
            vrv::Options *opts = tk.GetOptionsObj();
            opts->m_unit.SetValue(unit);
            opts->m_spacingLinear.SetValue(computeSpacingLinear(unit));
            tk.RedoLayout();
            return pageTarget < tk.GetPageCount();
        });
    return target == units.end() ? MAX_UNIT : *target - 1;
}
```

Note that this code was written with the old (pre-3.13.0) unit limits in mind. We plan to update it eventually.
