### ISSUE TITLE
verovio 3.15   Load files multiple times without emptying the data

### ISSUE THREAD

**Issue by junke365** [rism-digital/verovio#3338]
![image](https://user-images.githubusercontent.com/25856057/226512909-16720233-b2ec-4353-9385-b7b4252a3256.png)
![image](https://user-images.githubusercontent.com/25856057/226512958-9c79a93f-afb7-46a4-9274-f68a60a16b90.png)
![image](https://user-images.githubusercontent.com/25856057/226512986-af05dc0b-6d05-4954-9af4-597ce60aee4d.png)
The first load is 122 and the second load is adding up to 244, and the previous memory is not cleared,

**Comment by lpugin** [comment]
Please fill the issue template with:

**Describe the problem**
A clear and concise description of what the problem is.

**To Reproduce**
Steps to reproduce the behavior:
1. Load the data attached
2. Render page X
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Input data**
The smallest example (MEI unless about another input format) to reproduce the problem

**Verovio information**
 - Version of Verovio [e.g. develop, 3.4.0]
 - Binding [e.g. command-line, JavaScript, Python]

**Environment information (as appropriate)**
 - OS: [e.g. MacOS, Window]
 - Browser [e.g. Chrome, Safari]

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by junke365** [comment]
Okay, my own problem, I wrote the read interface,

**Comment by junke365** [comment]
Many thanks
