### ISSUE TITLE
`systemMaxPerPage` not working

### ISSUE THREAD

**Issue by sonovice** [rism-digital/verovio#3369]
**Describe the problem**
The option `systemMaxPerPage` has no effect. I wanted to only render the first system by setting the value to 1.

**To Reproduce**
1. Load any MEI file with Verovio
2. Set `systemMaxPerPage` to anything > 0
3. No profit :wink: 

**Verovio information**
 - Version of Verovio: develop
 - Binding: JS

**Environment information (as appropriate)**
 - OS: Linux
 - Browser: Chrome

**Comment by craigsapp** [comment]
I am getting the same result (checking with a recent version of verovio this time :-)

I have been making musical incipits with other option settings since before this option was added, which should work in the meantime:

```
verovio --page-height 100  --adjust-page-height 
```

This sets the page height to the minimum, and then adjusts the page height to the height of the rendered music, which forces only a single system to be generated.
