### ISSUE TITLE
Inconsistent positioning of stems and beams

### ISSUE THREAD

**Issue by frakel** [rism-digital/verovio#3390]
From Verovio 3.7+ stem directions for beamed notes are somehow inconsistent. See this example from StrQ. K. 159/2, 2nd Violin:
![image](https://user-images.githubusercontent.com/5627140/233630068-5bb1a25b-c1b8-4870-ae2a-f973211b5066.png)
<details><summary>MEI Code:</summary>
<p>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.1/mei-CMN.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.1/mei-CMN.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title label="NMA digital" type="unit">inconsistent stem dir</title>
            <contributor>dime</contributor>
         </titleStmt>
         <pubStmt/>
      </fileDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef meter.count="3" meter.sym="common" meter.unit="4">
                  <staffGrp>
                     <staffDef clef.line="2" clef.shape="G" lines="5" n="1" xml:id="sd1"/>
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure n="43" xml:id="m1">
                     <staff n="1">
                        <layer n="1" xml:id="layer_10800">
                           <beam xml:id="beam_10806">
                              <note accid.ges="n" dur="8" oct="4" pname="a" xml:id="note_10812"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_10818"/>
                              <note accid.ges="n" dur="8" oct="5" pname="c" xml:id="note_10824"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_10830"/>
                              <note accid.ges="f" dur="8" oct="5" pname="e" xml:id="note_10836"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_10842"/>
                           </beam>
                        </layer>
                     </staff>
                  </measure>
                  <measure n="44">
                     <staff>
                        <layer n="1" xml:id="layer_10974">
                           <beam xml:id="beam_10980">
                              <note accid.ges="n" dur="8" oct="5" pname="c" xml:id="note_10986"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_10992"/>
                              <note accid.ges="n" dur="8" oct="4" pname="a" xml:id="note_10998"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_11004"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_11010"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_11016"/>
                           </beam>
                        </layer>
                     </staff>
                  </measure>
                  <measure n="45">
                     <staff>
                        <layer n="1" xml:id="layer_11148">
                           <beam xml:id="beam_11154">
                              <note accid.ges="n" dur="8" oct="4" pname="a" xml:id="note_11160"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_11166"/>
                              <note accid.ges="n" dur="8" oct="5" pname="c" xml:id="note_11172"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_11178"/>
                              <note accid.ges="f" dur="8" oct="5" pname="e" xml:id="note_11184"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_11190"/>
                           </beam>
                        </layer>
                     </staff>
                  </measure>
                  <measure n="46">
                     <staff>
                        <layer n="1" xml:id="layer_11328">
                           <beam xml:id="beam_11334">
                              <note accid.ges="n" dur="8" oct="5" pname="c" xml:id="note_11340"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_11346"/>
                              <note accid.ges="n" dur="8" oct="4" pname="a" xml:id="note_11352"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_11358"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_11364"/>
                              <note accid.ges="n" dur="8" oct="4" pname="f" xml:id="note_11370"/>
                           </beam>
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```
</p>
</details>

Could this be rendered more homogeneous again?

**Comment by craigsapp** [comment]
There is no homogeneous beam-placing system in verovio (yet).

However, I am finding the 3.16 version more readable since the melodic line in measures 1 and 3 (A-C-E) stands out more So it is debatable about which one is better, and it is probably best to manually encode the stem directions in this case rather than rely on an automatic choice.

**Comment by rettinghaus** [comment]
This is what Glould (p 24) says: 

<img width="584" alt="image" src="https://user-images.githubusercontent.com/7693447/233637628-93982153-023c-438e-8edb-5d1b221f8e22.png">

So from map point of view it is now correctly and better than before.

If you _need_ them to be in a specific direction, why not encode them this way?

**Comment by frakel** [comment]
ok, thank you @craigsapp @rettinghaus  for commenting on this. I know it's a problem of little priority. And music layout is very often a question of context and taste ... But as Verovio changed its behaviour in this regard from 3.7 onwards I wanted to mention it here, as in our specific context of K.159 the more uniform rendering of 3.6 was better. Manually tweaking layout paramaters is and should always be the last remedy

**Comment by craigsapp** [comment]
Here is the full quotation about beam directions in Behind Bars:

<img width="434" alt="Screenshot 2023-04-21 at 7 24 16 AM" src="https://user-images.githubusercontent.com/3487289/233661682-6db00599-5b65-4caf-9a2b-dc8fabf75a01.png">

<img width="431" alt="Screenshot 2023-04-21 at 7 24 25 AM" src="https://user-images.githubusercontent.com/3487289/233661696-de695ac3-b159-41f1-a57e-bb887e63438a.png">

What your are wanting is the last section "Visual considerations".   Having a computer algorithm make such decisions is difficult, and it will never be able to do it 100% correctly.   At some point human judgement by someone who can sightread music is necessary (the ability to sightread is important because they can evaluate which layout is easier to read).  Many rules for music notation typesetting are oriented towards maximizing sightreadability of the music, but ultimately this is subjective for various reasons such as the musician being familiar with a particular layout rule and can even be different for different instruments.

As the no. 1 issue submitter (complainer :-) to verovio, I have several times thought about adding an issue about this rule.  But I cannot imagine how it would be implemented in a productive way that you would not then have to fix cases where the algorithm got it wrong.  To implement it would take some work, and after it is done, there would still be cases to fix or unfix, so I cannot imagine that such a feature would save any time when preparing a score.

In general _Behind Bars_ should be the reference style for verovio since it gives the modern conventions for music typesetting.   When encoding diplomatic editions of older scores (or newer scores based on the notation style of older editions), then this can be done by explicitly encoding the layout, particularly when it goes against more modern layout rules.

As a case example, The Chopin Institute's digitization projects encode diplomatic versions of the source editions, and every single stem direction is encoded in the digital score.  Example work:

https://polishscores.org/?id=18xx:3540

<img width="1115" alt="Screenshot 2023-04-21 at 7 40 53 AM" src="https://user-images.githubusercontent.com/3487289/233664765-f60f94ca-c1a5-4839-846c-010b352e5a6c.png">

You can view the source edition by clicking on the file icon below the library name:

<img width="385" alt="Screenshot 2023-04-21 at 7 41 36 AM" src="https://user-images.githubusercontent.com/3487289/233664946-971925af-260b-4dd0-ae44-36c7259b59ba.png">

https://polona2.pl/item/pieces-favorites,MTk4NjI5Mw/4/#info:metadata

<img width="1504" alt="Screenshot 2023-04-21 at 7 43 20 AM" src="https://user-images.githubusercontent.com/3487289/233665366-79574112-d449-45c1-96ea-c282e8898937.png">

The stem directions match between the scan and the diplomatic digital edition, and it will still match if verovio changes its stem/beam direction rules.   On the polishscores.org workpage show above, there is an "O" button in the top toolbar.  This "O" means it is showing the original layout (system breaks are encoded but not shown on the website).  If you click on the "O" it will change view to the modernized score and replace the "O" with an "M", meaning your are viewing the modernized score.  In this case the stem directions are remove:

<img width="1020" alt="Screenshot 2023-04-21 at 8 10 18 AM" src="https://user-images.githubusercontent.com/3487289/233671736-925b2a79-b512-4bb9-b181-bf35b0de7956.png">

I disagree with the stem directions of the grace notes, since they should be opposite to the main notes.  In the future I will add an option to preserve explicit stem/beam directions in the modernized score (that would otherwise be placed in the wrong/undesired direction in verovio).

Here is a view of the same score in VHV along with the Humdrum digital score:

https://verovio.humdrum.org/?file=https%3A%2F%2Fdata.nifc.humdrum.org%2F18xx%3A3540.krn&filter=shed%20-e%20%27s%2F%5Ecustos%2FCustos%2FI%27

<img width="1157" alt="Screenshot 2023-04-21 at 8 16 04 AM" src="https://user-images.githubusercontent.com/3487289/233673033-d36667a7-2032-47a9-8f76-75f9924a476c.png">

Notice the `/` for stem up and `\` for stem down in the text on the left.  

Applying the modernization transformations to the score:

https://verovio.humdrum.org/?file=https%3A%2F%2Fdata.nifc.humdrum.org%2F18xx%3A3540.krn&filter=shed%20-e%20%27s%2F%5Ecustos%2FCustos%2FI%27%20%7C%20filter%20-v%20modern

<img width="1157" alt="Screenshot 2023-04-21 at 8 22 24 AM" src="https://user-images.githubusercontent.com/3487289/233674538-43826523-d97c-4ef6-a8b5-4c3f372bf6e6.png">

Now notice that the stem directions in the text on the left are removed.

Here is the "modern" filter line at the bottom of the score:

```
!!!Xfilter-modern: | autostem -r | shed -e "s/TUP/tup/L; s/^(X)?tuplet/$1TUPLET/I" | shed -k -e “s/([^a-gA-Gn#X-])[<>]/$1/g”  | modori -m
```

which has these components:

<dl>
<dt> <code>autostem -r</code> </dt>
<dd> Remove explicit stem directions </dd>
<dt> <code>shed -e "s/TUP/tup/L; s/^(X)?tuplet/$1TUPLET/I"</code> </dt>
<dd> Add modern tuplet styling and remove diplomatic tuplet styling.</dd>
<dt> <code>shed -k -e “s/([^a-gA-Gn#X-])[<>]/$1/g”</code> </dt>
<dd> Remove explicit staff placement for everything other than cross-staff notes</dd>
<dt> <code>modori -m</code> </dt>
<dd> Display modern versions of various things (see <a href="https://doc.verovio.humdrum.org/filter/modori">modori</a> filter documentation)</dd>
</dl>
