### ISSUE TITLE
Custom Head.shape from SMuFL fonts

### ISSUE THREAD

**Issue by faelwar** [rism-digital/verovio#3504]
**Describe the problem**
I'm trying to change head.shape of my encoding with the following MEI code:
```
<note oct="5" pname="b" head.auth="smufl" head.shape="U+E0AA" />
```
But it does not show the correct notehead.

**To Reproduce**
1 - Adding the above MEI and try to render it.

**Expected behavior**
It should show a note with a Ornate X as the notehead

**Input data**
```
<note oct="5" pname="b" head.auth="smufl" head.shape="U+E0AA" />
```

**Verovio information**
 - Verovio 3.16.0

**Environment information (as appropriate)**
 - OS: MacOS
 - Browser Firefox

**Comment by faelwar** [comment]
How do I use then on verovio?

**Comment by lpugin** [comment]
You cannot because currently Verovio supports only `data.HEADSHAPE.list` from [`data.HEADSHAPE`](https://music-encoding.org/guidelines/v5/data-types/data.HEADSHAPE.html).

When support for `data.HEXMUM` is added, it will also be necessary to add `U+E0AA` to the Leipzig font since this glyph is not in it yet. See the list of glyphs [here](https://torinak.com/font/lsfont.html#https://raw.githubusercontent.com/rism-digital/leipzig/main/Leipzig.otf).

**Comment by faelwar** [comment]
That Makes a lot of sense, thanks for the explanation.
