### ISSUE TITLE
RuntimeInitialized not getting called

### ISSUE THREAD

**Issue by faelwar** [rism-digital/verovio#3523]
**Describe the problem**
I just built the Javascript lib from develop and from the master. And the RuntimeInitialized Callback is never called. I took a look into the built coded and on the code generate by me does not contains a any mention of the RuntimeInitialized on it. While the zip on the Release here does have.

**To Reproduce**
1. Just run ./buildToolkit -w -H

**Expected behavior**
I should have the mention to the RuntimeInitialized

**Input data**
no input need

**Verovio information**
 - develop
 - Javascript

**Environment information (as appropriate)**
 - OS: [MacOS Sonoma
 - Browser Safari and Firefox

**Comment by lpugin** [comment]
The callback is called `onRuntimeInitialized`. What do you mean "is never called"? This is the principle of a callback, it is not called in the code but when the module is loaded.

Both develop and master branch do work, so the problem is not clear and the information you are providing to reproduce the problem are not enough. Also, please make sure you use the latest version for the emsdk.
