### ISSUE TITLE
Humdrum input sometimes generates a note with no `@dur` (but with `@dots`, `@dur.ges`, and `@dots.ges`

### ISSUE THREAD

**Issue by gregchapman-dev** [rism-digital/verovio#3542]
**Describe the problem**
Triggered by a tuplet with a visual duration (I think), iohumdrum.cpp will fail to generate a `@dur` value.  I believe the problem is because visual duration is getting the tuplet multiplier applied, when it should not (it should not, I think, when it is the visual duration that is NOT also the gestural duration).  The result is that getDurAndDots() returns NONE for dur.  I tried removing the code that did this incorrect tuplet multiplier application, but later in convertRhythm, setRhythmFromDuration was called, which also applies the tuplet multiplier.  I believe that in the presence of both visual and gestural durations, setRhythmFromDuration should not be called here.  But it is not clear to me what the exact logic should be, since there are redundant calculations in this case.

**To Reproduce**
1. Convert the attached Humdrum snippet to MEI using Verovio.
2. Look at resulting MEI.
3. See that the first note of staff 2 has no `@dur`:
         `<note xml:id="note-L10F5" dots="1" dur.ges="breve" dots.ges="0" oct="3" pname="d" accid.ges="n">`

**Expected behavior**
`@dur` should be present, and (I _think_) should be "breve".

**Input data**
The attached Humdrum snippet.

**Verovio information**
 - Version of Verovio: humdrum-develop
 - Binding: command line (or verovio.humdrum.org)

**Environment information (as appropriate)**
 - OS: MacOS
 - Browser: Safari

[Snippet-Ano1026d-Missa_Gross_senen-Sanctus--Trent_89.krn.zip](https://github.com/rism-digital/verovio/files/13273554/Snippet-Ano1026d-Missa_Gross_senen-Sanctus--Trent_89.krn.zip)

```tsv
**kern	**text	**kern	**text	**kern	**text	**kern	**text
*part4	*part4	*part3	*part3	*part2	*part2	*part1	*part1
*staff4	*staff4	*staff3	*staff3	*staff2	*staff2	*staff1	*staff1
*clefF4	*	*clefGv2	*	*clefGv2	*	*clefG2	*
*k[b-e-]	*	*k[b-]	*	*k[b-]	*	*k[b-]	*
*M2/1	*	*M2/1	*	*M2/1	*	*M2/1	*
*met(C|)	*	*met(C|)	*	*met(C|)	*	*met(C|)	*
=235	=235	=235	=235	=235	=235	=235	=235
!	!	!	!	!LO:N:vis=0.	!	!	!
0r	.	0r	.	[y3%4D	in	[0a	in
.	.	.	.	3%2D]yy	.	.	.
==	==	==	==	==	==	==	==
*-	*-	*-	*-	*-	*-	*-	*-
```

**Comment by gregchapman-dev** [comment]
The note in the Humdrum file is written as:
=235
!LO:N:vis=0.
[y3%4D

It's clearly wrong to take 0. (dotted breve) and multiply it by the tupletMultiplier computed from 3%4 to get `@dur` and `@dots`.  Rather, I think, `@dur` should be "breve" and `@dots` should be "1".  But how to make that happen?

**Comment by craigsapp** [comment]
Here is the target rendering (useing muse2ps rather than verovio):

https://josquin.stanford.edu/cgi-bin/jrp?a=notationEditText&f=Ano1026d

<img width="775" alt="Screenshot 2023-11-06 at 16 01 20" src="https://github.com/rism-digital/verovio/assets/3487289/e6d6c941-892f-4df0-8da1-a4d99dbd6df6">

The note should be `3%4.` (triplet dotted breve) but I split it into two pieces and make the second half invisible to get the triplet bracket to show more properly (muse2ps cannot display tuplet brackets on single notes; verovio also has problems but slightly better).

Adding `@dur="breve"` to the first note of the tie group (tuplet) will fix the problem:

<img width="961" alt="Screenshot 2023-11-06 at 16 05 01" src="https://github.com/rism-digital/verovio/assets/3487289/91694d72-61bf-48e3-b079-b71232da7d58">

There was likely a failure to calculate "breve" duration and the converter gave up.

(This is a complicated example, and I have not checked such cases in verovio yet, so it is good that you are doing it :-)

**Comment by craigsapp** [comment]
Fixed with commit https://github.com/rism-digital/verovio/commit/8a54f649d0393983367b5e449a74c0b643d97cc1

The problem occurs in `HumdrumInput::getDurAndDots()`.  The function was trying to remove the tuplet factor from the duration with this line:

```cpp
dur *= m_tupletscaling;
```

But `HumdrumInput::convertRhythm()` had already removed the tuplet factors for the duration before calling `getDurAndDots()`.

The best solution is to add the tuplet factors back in before calling `getDurAndDots()`, and then let that function remove them.   This is because there are two other functions that call `getDurAndDots` (`setRhythmFromDuration` and `setVisualAndGesturalRhythmFromDuration`) that do not remove the tuplet component of the duration before calling `getDurAndDots`.

Test example:

```tsv
**kern	**kern
*clefGv2	*clefG2
*M2/1	*M2/1
*met(C|)	*met(C|)
=	=
!LO:N:vis=0.	!
3%4.D	[0a
=	=
!LO:N:vis=0.	!
[y3%4D	0a_
3%2D]yy	.
=	=
*-	*-
```

Now rendering as expected:

<img width="690" alt="Screenshot 2023-11-06 at 22 46 37" src="https://github.com/rism-digital/verovio/assets/3487289/29fbd456-8ba9-4723-99d3-ee3b109705d7">

<details>
<summary> Click to view MEI conversion of above Humdrum data </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/5.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2023-11-06T22:47:41" version="4.1.0-dev-1689969">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mtkgyxr">
    <score xml:id="s3a65x3">
     <scoreDef xml:id="s1gmffx8" midi.bpm="400.000000">
      <staffGrp xml:id="sh033jf" bar.thru="true" symbol="brace">
       <staffDef xml:id="staffdef-L1F2" n="1" lines="5">
        <clef xml:id="clef-L2F2" shape="G" line="2" />
        <meterSig xml:id="metersig-L3F2" count="2" unit="1" visible="false" />
        <mensur xml:id="mensur-L4F2" sign="C" slash="1" />
       </staffDef>
       <staffDef xml:id="staffdef-L1F1" n="2" lines="5">
        <clef xml:id="clef-L2F1" shape="G" line="2" dis="8" dis.place="below" />
        <meterSig xml:id="metersig-L3F1" count="2" unit="1" visible="false" />
        <mensur xml:id="mensur-L4F1" sign="C" slash="1" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1">
       <staff xml:id="staff-L1F2" n="1">
        <layer xml:id="layer-L1F2N1" n="1">
         <note xml:id="note-L7F2" dur="breve" oct="4" pname="a" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L1F1" n="2">
        <layer xml:id="layer-L1F1N1" n="1">
         <tuplet xml:id="tuplet-L7F1" num="3" numbase="2" num.format="count">
          <note xml:id="note-L7F1" dots="1" dur.ges="breve" dots.ges="1" dur="breve" oct="3" pname="d" accid.ges="n" />
         </tuplet>
        </layer>
       </staff>
       <tie xml:id="tie-L7F2-L10F2" startid="#note-L7F2" endid="#note-L10F2" />
      </measure>
      <measure xml:id="measure-L8">
       <staff xml:id="staff-L8F2N1" n="1">
        <layer xml:id="layer-L8F2N1" n="1">
         <note xml:id="note-L10F2" dur="breve" oct="4" pname="a" accid.ges="n" />
        </layer>
       </staff>
       <staff xml:id="staff-L8F1N1" n="2">
        <layer xml:id="layer-L8F1N1" n="1">
         <tuplet xml:id="tuplet-L10F1-L11F1" num="3" numbase="2" num.format="count">
          <note xml:id="note-L10F1" dots="1" dur.ges="breve" dots.ges="0" dur="breve" oct="3" pname="d" accid.ges="n" />
          <note xml:id="note-L11F1" type="no-attack" dur="1" oct="3" pname="d" visible="false" accid.ges="n" />
         </tuplet>
        </layer>
       </staff>
       <tie xml:id="tie-L10F2-L12F2" type="hanging-terminal" staff="1" startid="#note-L10F2" tstamp2="0m+3.0000" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>
