### ISSUE TITLE
voice problem in two voices

### ISSUE THREAD

**Issue by dajun-TT** [rism-digital/verovio#3752]
**Describe the problem**
When an augmented octave is tied to the last measure, it causes the second voice to lose the effect of the augmented octave, with the actual melody being played at the original pitch (in the case of only two voices).
![image](https://github.com/user-attachments/assets/bf0610ae-e63b-4266-8605-e8e9ddd40da0)
![image](https://github.com/user-attachments/assets/48969c18-d837-4aa9-874d-77ecb7caabb1)

**Comment by dajun-TT** [comment]
Similarly, when applying diminished octaves, augmented 15ths, or diminished 15ths, the effect is the same. Even though they fall within the tied range, the pitch remains at the original pitch.
![image](https://github.com/user-attachments/assets/064837fb-94c8-4f7e-bf76-ca9aa23b3d18)
![image](https://github.com/user-attachments/assets/0a016d69-d8b1-42f1-a76c-89b46039237e)

**Comment by craigsapp** [comment]
Your description is not understandable because you do not use musical terms in a standard manner (e.g., "tie", "augmented", "diminished").   

To make the problem clear and allow fixing of the problem, you must provide input data that produces the music notation you  provide (either in MusicXML or MEI format). 

You can attach musical examples by dragging a MusicXML or MEI file onto the message, maybe in a ZIP file (images of the input data are not useful because the input data is needed to reproduce the problem and use to fix the problem).   

For smaller example files less than about 1000 lines, you can paste the MusicXML/MEI file's contents directly into the website:

````
```xml
[paste contents of MusicXML or MEI file here]
```
````

For longer examples, it is better to paste into the message in this format:


````
<details>
<summary> Click to view MEI/MusicXML example data </summary>

```xml
[paste contents of MusicXML or MEI file here]
```

</details>
````

**Comment by lpugin** [comment]
Unless proven otherwise this is a problem in the data.
