### ISSUE TITLE
Rests overlap with notes when placed inside octaves.

### ISSUE THREAD

**Issue by dajun-TT** [rism-digital/verovio#3755]
**Describe the problem**
As shown in the image, the rest symbols often overlap with the note positions. It's frequently necessary to manually drag the rest to reposition it properly.
![image](https://github.com/user-attachments/assets/f7df48fb-d21e-4395-b1e3-d6ebc04d87b3)

**Comment by rettinghaus** [comment]
Please provide a minimal MEI example.

**Comment by craigsapp** [comment]
As always, you should provide example MusicXML or MEI data that is used to create the music notation example, otherwise the problem will not be fixed.

A music notation typesetting program cannot always place rests correctly, although this case could be handled automatically (but see my comments below where this could be a data error and otherwise a MusicXML/MEI data limitation).

I have encountered this problem before, and the main complication is that the quarter-note rest is too large to fit inside of the octave:

<img width="742" alt="Screenshot 2024-09-01 at 9 49 23 PM" src="https://github.com/user-attachments/assets/c87c4894-cec6-4a67-85cd-99db85dd5c97">

Note in the first measure, the automatic placement of rests are as expected in verovio based on the layer information of the notes/rests.   Since your example places the note inside of the octave, it is a data error most likely. (and in that case the source data needs to be supplied for study).

Measure 2 gives explicit placement of the rest between the octave.  In this case the rest is too larger, and the notation is not acceptable.  Either the rests must be offset to the left/right so as not to not touch the notes, or the rests must be made smaller (that is what the source edition did in the case that I have come across).

Also it would be useful to provide an image of this case in your source music notation program's rendering of the notation to see what it looks like.

The last measure gives some additional solutions for making the rest smaller.

* purple: `@cue="true"`.  This basically works, but is not the ideal use of `@cue` (it is not a *cue* note but rather a *cue-sized* note.).  This is currently the most acceptable solution, but ideally the rest would be placed 1/2 diatonic step down to not touch the upper note in the octave.
* green: `@cue="true"` but I place on the F space rather than the G line.  The purple one is a bit too high and the green one is a bit too low.  Ideally verovio would detect octave/rest cases like this and place between G line and F space at a fractional `@loc` since `@ploc`/`@oloc` cannot handle this case.
* orange/red: In these cases I try `rest@fontsize`.  This feature is not implemented yet in verovio.  As an aside, it would be useful to have `rest@fontsize="cue"` added to MEI:
https://music-encoding.org/guidelines/v5/data-types/data.FONTSIZETERM.html

On the red rest I tried `@loc="1.5"`  This is not allowed in MEI (and by extension verovio), so "1.5" is converted into "1" by verovio.  It might be good to allow fractional `@loc` for cases such as this.

Notice for the green rest that it is colliding with the stem of the chord, and in such cases the horizontal placement of the rest should be that the right side of the rest is aligned with the right side of the notes (or a fixed horizontal offset should be set automatically).

**Comment by ahankinson** [comment]
Closing due to lack of further details.
