### ISSUE TITLE
Relationship between the musicxml and the output(svg)

### ISSUE THREAD

**Issue by stereomatchingkiss** [rism-digital/verovio#3760]
I check the doc. After study the doc, svg and musicxml, I have some questions

1. The svg output do not contains the details of the music sheet(like it is 4 or 2).
2. The svg generated by the musicxml has some different compare with [MozaChloSample.musicxml](https://drive.google.com/file/d/1OfM3tINPAAso01Lcs0q8v6Z4kjWRB7hI/view?usp=drive_link), [golden sample](https://drive.google.com/file/d/1Rq6fEeqivYhgW5SYZ6nFWcVrZ-cB5Mb9/view?usp=drive_link) of this musicxml, [generated svg](https://drive.google.com/file/d/1Ouo_wY9oRPCG_yyLvH1rvpK3_xpDD4oW/view?usp=drive_link). I download them from [here](https://www.musicxml.com/music-in-musicxml/example-set/). Is it because the features haven't completed yet?

If 1 is true(no surprise since svg just need the info to draw the graphics), that means I need to parse the musicxml and associate it to the output of the svg(I want to change the colors of the nodes according to some sort of rules, need to know the details of the music sheet)?

I guess I could assume the output of the svg would have the same order of the musicxml? Like I would read the measure from 1 to 100, and the svg would draw the measure from 1 to 100 too, sounds like make sense.

Thanks

**Comment by craigsapp** [comment]
> Verovio is based on MEI and not MusicXML, which gets converted.

Yes, but related to this secondary comment:

> The svg generated by the musicxml has some different compare with [MozaChloSample.musicxml](https://drive.google.com/file/d/1OfM3tINPAAso01Lcs0q8v6Z4kjWRB7hI/view?usp=drive_link), [golden sample](https://drive.google.com/file/d/1Rq6fEeqivYhgW5SYZ6nFWcVrZ-cB5Mb9/view?usp=drive_link) of this musicxml, [generated svg](https://drive.google.com/file/d/1Ouo_wY9oRPCG_yyLvH1rvpK3_xpDD4oW/view?usp=drive_link). I download them from [here](https://www.musicxml.com/music-in-musicxml/example-set/). Is it because the features haven't completed yet?

There are some enhancements likely needed in the MusicXML-to-MEI converter within verovio.

I examined the Mozart *An Chloe* example, which shows how to add accidental qualifications to `<turn>` in MusicXML 4.0 (these are officially produced files at least :-)   Feature enhancement for this is submitted in issue #3761. 

This was the only problem I found in the *An Chloe* conversion from MusicXML to MEI.   The verovio conversion is better than the one to Musescore 4.4, since Musescore did not convert the delayed turn in measure 4 correctly.   And verovio is otherwise equivalent to how Dorico v4 and Sibelius v8.3 load the turns, so they also have problems with the MusicXML sample import.   So no notation program other than Finale loads the *An Chloe* example MusicXML file properly.

If you want MusicXML to be displayed properly in verovio, you can submit an issue if you see something missing or incorrect.  I did the report for *An Chloe* in issue #3761, with comparisons to how the MusicXML data is loaded into other music notation program as part of the analysis.  I also give the MEI conversion that should be done (which would be useful to add, but not necessary if you don't know what the mapping should be).
